### ISSUE TITLE
Replace datamodel

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-examples#10]
The current examples are based on a weird datamodel which looks like the following

```graphql
type Cat {
  id: ID! @unique
  name: String!
  color: String!
  favBrother: Cat
}

type Master {
  id: ID! @unique
  catz: [Cat!]!
}
```

I suggest to base it on the following data model instead:

## Minimal

```graphql
type Post {
  id: ID! @unique
  isPublished: Boolean! @default(value: false)
  title: String!
  content: String!
}
```

## Basic

```graphql
type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean! @default(value: "false")
  title: String!
  content: String!
  author: User!
}

type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  name: String!
  posts: [Post!]!
}
```

This also means the resulting application should be adjusted to match the new datamodel.

**Comment by brikou** [comment]
IMO Post.content or Post.body is better than Post.text, because text may be confusing as too generic and remind a datatype.

**Comment by brikou** [comment]
For me the **Advanced** datamodel is too simple, we cannot demonstrate real world usage and so real world bug. We should add another model fe. **Comment** related to **Post**.

This way we could demonstrate how to **chain calls** and when to use **fragments**. One of the keypoint of this new release (1.17) is about chaining methods, so we need another model.
Another keypoint is the generated TS typing quality, to really test it another model is required.

ping @schickling 

NB: I'm really excited about 1.17 new features... great job prisma team!

**Comment by schickling** [comment]
Great point @brikou. I've renamed my datamodel suggestions from "Basic" -> "Minimal" and "Advanced" -> "Basic".

For more real-world (aka advanced) examples, please check out the "Reference Implementation" section in the readme: https://github.com/prisma/prisma-examples#reference-implementations

**Comment by schickling** [comment]
## Update

I've started updating the examples to the following datamodel:

```graphql
type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean! @default(value: "false")
  title: String!
  content: String!
  author: User!
}

type User {
  id: ID! @unique
  name: String!
  email: String! @unique
  posts: [Post!]!
}
```

For the GraphQL server examples I suggest the following application schema:

```graphql
scalar DateTime

type Query {
  feed: [Post!]!
  drafts: [Post!]!
  post(id: ID!): Post
}

type Mutation {
  createDraft(title: String!, content: String!, authorEmail: String!): Post!
  deletePost(id: ID!): Post
  publish(id: ID!): Post
}

type Post {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean!
  title: String!
  content: String!
  author: User!
}

type User {
  id: ID!
  email: String!
  name: String!
  posts: [Post!]!
}
```

For the `xxx-graphql-auth` examples, I suggest to add a `password: String!` field to the `User` in the datamodel.

**Comment by abhiaiyer91** [comment]
Great we'll run with this

**Comment by abhiaiyer91** [comment]
All prev data models using the Cat/Master setup is now using this data model
