### ISSUE TITLE
prisma2 generate default directory

### ISSUE THREAD

**Issue by lasharela** [prisma/prisma-examples#1069]
I'm trying to deploy `examples/javascript/graphql-auth` to Heroku.

the question is how to generate `src/generate` files.

And is this directory `src/generate` just old artifact?
Should I use `prisma2 generate` or `nexus-prisma` also?

I'm a little bit confused.

**Comment by batFormat** [comment]
@lasharela 
The same problem, when changing my scheme, files in this `src/generated` directory are not generated.
Do you have a solution?

**Comment by nikolasburk** [comment]
Hey @lasharela, thanks a lot for opening this issue. Were you able to resolve this?

**Comment by adrianoresende** [comment]
Try adding a script in package.json
`"heroku-postbuild": "npx prisma generate"`

**Comment by nikolasburk** [comment]
Closing this issue in an effort of cleaning up old issues. Feel free to reopen the issue if you still have questions @lasharela 🙌
