### ISSUE TITLE
Flutter client

### ISSUE THREAD

**Issue by gedw99** [prisma/prisma-examples#111]
Would you consider supporting Dart CLient too ?

Dart Lib for graphql
https://github.com/zino-app/graphql-flutter

Example
https://github.com/zino-app/graphql-flutter/blob/master/example/lib/main.dart

I use this with a graphql Golang server based on GQLgen now and its nice and clean flow.

**Comment by schickling** [comment]
Thanks a lot for this great suggestion. Can you open a feature request for a Dart client in the `prisma` repo similar to [this one](https://github.com/prisma/prisma/issues/3218)?

**Comment by gedw99** [comment]
hey @schickling 
Thanks for the opportunity to propose this. I find Flutter to be a huge time saver for Mobile and Desktop apps..
https://github.com/prisma/prisma/issues/3393

I suggested a few approaches also.

**Comment by nikolasburk** [comment]
Thanks so much for your initiative and thinking about a Flutter client for Prisma! I'm closing this issue since it doesn't really relate to any examples but rather to the general feature set of Prisma, so the FR  https://github.com/prisma/prisma/issues/3393 you created should be enough! 🙏

**Comment by brokercl** [comment]
Hi Nikolasburk
I follow your tutorial 

https://www.howtographql.com/react-apollo/1-getting-started/

 and it was excellent
but for now I would like to make the same but using flutter
I tried to read users from prisma but until now without any succsees result

thats why I encourage to you to try develop the same but this time using Flutter from Google

I could do this toturial satisfactorily

https://medium.com/flutter-community/building-a-simple-application-with-flutter-and-graphql-5786764df102

greetings
