### ISSUE TITLE
prisma2 introspection failed -windows

### ISSUE THREAD

**Issue by rakeshrana15** [prisma/prisma-examples#1204]
encountered prisma2 introspection failed error with mysql db on windows.

Schema parsing
error: Error validating model "profile": Each model must have exactly one id criteria. Either mark a single field with `
@id` or add a multi field id criterion with `@@id([])` to the model.
  -->  schema.prisma:18
![prisma2 introspection failed](https://user-images.githubusercontent.com/20044916/71303315-1842d880-23dd-11ea-9332-735f6e67bfb7.png)

**Comment by janpio** [comment]
Issue can now be found at https://github.com/prisma/prisma2/issues/1203
