### ISSUE TITLE
prisma2 dev failed with sqlite database

### ISSUE THREAD

**Issue by rakeshrana15** [prisma/prisma-examples#1206]
Prisma2 dev failed with sqlite database on windows

Error: Command failed with exit code 255: C:\Users\krakes\AppData\Roaming\npm\node_modules\prisma2\migration-engine.exe cli --datasource sqlite:// --create_database

![prisma2 dev error](https://user-images.githubusercontent.com/20044916/71307412-ffa1e500-2413-11ea-8b7c-6b173ced649c.png)

**Comment by janpio** [comment]
Duplicate of https://github.com/prisma/prisma2/issues/1201
