### ISSUE TITLE
TypeScript/GraphQL example includes workaround for a closed issue

### ISSUE THREAD

**Issue by dmzza** [prisma/prisma-examples#1219]
https://github.com/prisma/prisma-examples/blob/926fcf81207ae5f172f0ba52d9863fcc58ea3852/typescript/graphql/tsconfig.json#L12

Shouldn't this be `false` now that the related issue https://github.com/prisma/nexus-prisma/issues/82 has been fixed?

**Comment by janpio** [comment]
Ping @jasonkuhrt @Weakky

**Comment by jasonkuhrt** [comment]
It should be ok to remove now. Feel free to open a PR

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue David (and sorry for the delay!). We've adjusted all tsconfig.json files ✅ https://github.com/prisma/prisma-examples/blob/prisma2/typescript/graphql/tsconfig.json
