### ISSUE TITLE
Update READMEs while Prisma client is in preview

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-examples#130]
- [ ] Remove `yarn prisma` script usage for JS-based examples (more context [here](https://github.com/prisma/prisma-examples/issues/108))
- [ ] Add instructions how to install correct Prisma CLI (beta if needed)

**Comment by nikolasburk** [comment]
## Node

- [ ] node-cli-app
- [ ] node-graphql
- [ ] node-graphql-auth
- [ ] node-graphql-schema-delegation
- [ ] node-graphql-subscriptions
- [ ] node-rest-express
- [ ] node-script

## TypeScript

- [ ] typescript-cli-app
- [ ] typescript-graphql
- [ ] typescript-graphql-auth
- [ ] typescript-graphql-schema-delegation
- [ ] typescript-script

## Flow

- [ ] flow-graphql
- [ ] flow-script

**Comment by abhiaiyer91** [comment]
we merged https://github.com/prisma/prisma-examples/pull/141 from @marktani

**Comment by abhiaiyer91** [comment]
We still need to update for `typescript-circleci`

**Comment by abhiaiyer91** [comment]
@schickling @nikolasburk do we want the README to describe installing prisma globally at beta? currently we have upgraded to `beta` and added `prisma` as a script in package.json

**Comment by nikolasburk** [comment]
As discussed internally already, we don't want anyone to install the `@beta` of the CLI. As long as it's needed, let's have additional `cd` statements in the READMEs and then eventually remove them once the Prisma CLI can detect prisma.yml in subfolders.
