### ISSUE TITLE
Build a REST API with Prisma client and Fastify

### ISSUE THREAD

**Issue by Aperrix** [prisma/prisma-examples#1395]
Hi everyone !

I didn't find API example with another framework than [Express](https://expressjs.com/). But as you all know [Express](https://expressjs.com/) is old and slow.

So i did a boilerplate with **[Fastify](https://www.fastify.io/)** for you. :heart: 

https://github.com/Aperrix/prisma2-fastify

Enjoy !

**Comment by nikolasburk** [comment]
Hey @Aperrix, sorry for the huge delay on this one! This actually looks great, do you want to submit this as a PR to this repo? Ideally as JS and TS versions? Would be much appreciated!

**Comment by por** [comment]
It looks like the project is gone @Aperrix?

**Comment by Aperrix** [comment]
Excuse me, I did some cleaning on my github, I thought that my proposal would be refused but if it interests you I will publish them again, stay around I don't have long 😃

**Comment by por** [comment]
I was just doing some investigation, I don’t think I’ll go for this approach for my project. But I think you can safely close this issue then.

**Comment by Aperrix** [comment]
> I was just doing some investigation, I don’t think I’ll go for this approach for my project. But I think you can safely close this issue then.

It's a shame, I developed a private API with fastify and prisma2 and it's a real pleasure

**Comment by por** [comment]
Hmm. I am sold on Fastify at the moment, but was a bit put off by hearing that Prisma2 has a bit too much magic going on (like most other ORMs), and the fact that migrations have an experimental flag, which seems to be quite an essential thing to have for me. I wonder how it scales past a certain point.

**Comment by janpio** [comment]
Hey @Aperrix, still looking forward to seeing that example again - possibly directly as a PR here.

**Comment by Aperrix** [comment]
> Hey @Aperrix, still looking forward to seeing that example again - possibly directly as a PR here.

Hey ! Nice to read you ! 

I was waiting for version 3 of fastify for ever more incredible performance! Now that it is available, I would be happy to redo the boilerplate

**Comment by gregbenner** [comment]
@Aperrix looking forward to seeing the boilerplate, sounds good!

**Comment by Aperrix** [comment]
@janpio javascript version is working perfectly but didn't pass your tests <https://github.com/prisma/prisma-examples/pull/1953>

**Comment by janpio** [comment]
Will answer in the PR 👍
