### ISSUE TITLE
Update Photon to Prisma Client in example docs

### ISSUE THREAD

**Issue by hatchli** [prisma/prisma-examples#1397]
I'm attempting to deploy the Javascript GraphQL Apollo Server [example ](https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-apollo-server)to Zeit Now. The [documentation ](https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/zeit-now) for deployment currently refers to Photon. 

I simply want to access the deployed GraphQL playground. What exactly would the index.js file be in the Javascript GraphQL Apollo server example, using Prisma Client Js?

**Comment by pantharshit00** [comment]
Hi @hatchli,

Thanks for reporting this. I would like to keep this open and refer to this as a docs issue.

**Comment by steebchen** [comment]
This is true for most examples, we still use `photonjs` there. This should be updated ASAP.

**Comment by nikolasburk** [comment]
Just added a note about that to the README. Right now only the `javascript` and `typescript` examples are expected to work. The rest is indeed outdated and should be cleaned up eventually.

**Comment by janpio** [comment]
Can we just create a branch of the current state, and then delete them from the main branch? No need to confuse people.

**Comment by nikolasburk** [comment]
Followed @janpio's advice and pushed the unmaintained examples to a [new branch](https://github.com/prisma/prisma-examples/tree/deployment-platforms/unmaintained). All other examples have been fixed thanks to the awesome work of @2color  🚀
