### ISSUE TITLE
Remove `schema.backup.prisma` 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-examples#1410]
@nikolasburk It was removed from current alpha with https://github.com/prisma/prisma2/issues/1369

So this will need to be updated for next preview :)

**Comment by nikolasburk** [comment]
Removed this from examples: https://github.com/prisma/prisma-examples/pull/1432

Also added a warning in the docs that the current Prisma schema file will be overridden: https://github.com/prisma/prisma2/pull/1569/files#diff-f29e2e5e999408f11b36aaad1550b2f4
