### ISSUE TITLE
golang prisma-client access relations in a single object query

### ISSUE THREAD

**Issue by patrickdevivo** [prisma/prisma-examples#142]
Right now, it seems like it's only possible in the golang generated client code to query for an object OR it's relation, not both. This _seems_ possible in the Typescript as such:

```ts
const linksByUser: LinkNode[] = await prisma
  .user({ email: "alice@prisma.io" })
  .links()
```

It would be useful if were possible to get a single object AND a relation(s) in a single query (is this not a main purpose of GraphQL?) rather than just one (the object) or the other (the relation)

**Comment by divyenduz** [comment]
In TS, this will return just the array of links and not user with links. To do that in TS client, we need to do the following. 

```typescript
const linksByUser: LinkNode[] = await prisma
  .user({ email: "alice@prisma.io" })
  .$fragment(`fragment u on User { id name links { url } } `)
```

This fragment API is however, not present in Go yet and must be implemented.

**Comment by patrickdevivo** [comment]
@divyenduz I understand now, I didn't realize it was the fragment API that was necessary here. That would be very useful in the golang generated client code!

**Comment by nikolasburk** [comment]
I'm closing this issue as it doesn't seem to be related to the examples but rather asks for a features (the `$fragment` API) in the Go client. There's already an open feature request for that in the main Prisma repo: https://github.com/prisma/prisma/issues/3322
