### ISSUE TITLE
Automatically recommend VSCode extension in example project by including in Workspace file

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1425]
![image](https://user-images.githubusercontent.com/183673/74524318-1863de00-4f1f-11ea-9e78-271656a6d41a.png)

![image](https://user-images.githubusercontent.com/183673/74524449-595bf280-4f1f-11ea-8ba7-4ba536366549.png)

![image](https://user-images.githubusercontent.com/183673/74524479-65e04b00-4f1f-11ea-809b-02d944fb2575.png)

See internal Slack thread: https://prisma-company.slack.com/archives/CFRDLGR8W/p1571393036029300

**Comment by matthewmueller** [comment]
Isn't this actually a Niko this? `.vscode/` is a folder in the `examples/`

**Comment by janpio** [comment]
Yep, pattern matching "VSCode" led to wrong assignments. Fixed.

**Comment by nikolasburk** [comment]
Added via https://github.com/prisma/prisma-examples/pull/1457
