### ISSUE TITLE
Follow best practices for Docker

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-examples#1437]
Our [Dockerfile](https://github.com/prisma/prisma-examples/blob/prisma2/deployment-platforms/docker/Dockerfile) for our docker example seems a bit hacky and outdated. I'd like to update this file to follow best practices.

**Comment by nikolasburk** [comment]
Note: I've adjusted this issue's title to reflect that the Docker examples is currently broken and that it needs to be cleaned up. I'll therefore close these two issues as duplicates: 

- https://github.com/prisma/prisma-examples/issues/916
- https://github.com/prisma/prisma-examples/issues/844

**Comment by ManAnRuck** [comment]
only news on this? now there is no docker file anymore :o

**Comment by Jolg42** [comment]
Closing as the Dockerfile was removed and opened an issue to add a Dockerfile example :) https://github.com/prisma/prisma-examples/issues/1856
