### ISSUE TITLE
Set up basic tests in CI

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-examples#1439]
We should make sure our examples have small basic tests to make sure they compile and are runnable. This should be as minimal as possible, since we already cover testing various tools in https://github.com/prisma/prisma2-e2e-tests.

**Comment by steebchen** [comment]
related https://github.com/prisma/prisma2/issues/1572

**Comment by janpio** [comment]
Not discussion about individual checks vs. 1 big check here: https://github.com/prisma/prisma-examples/pull/1487#issuecomment-590515371 + https://github.com/prisma/prisma-examples/pull/1487#issuecomment-590721191
