### ISSUE TITLE
Clean up issues, pull requests and branches

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1440]
There quite a few branches, Pull Requests and issues open for prisma-examples:

https://github.com/prisma/prisma-examples/issues
https://github.com/prisma/prisma-examples/pulls
https://github.com/prisma/prisma-examples/branches/all?page=1

It would be great if those could be cleaned up more.

**Comment by nikolasburk** [comment]
Thanks Jan! Just clean up PRs, branches and issues. All the open issues are valid and need to be looked into (none of them seem to be urgent though).
