### ISSUE TITLE
TypeScript examples don't compile with `tsc`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#1476]
Currently, the `typescript/graphql-auth` example works when following the instructions from the README:

```
npm install
npm run dev
```

This starts the server as expected and you can send queries to it.

However, when compiling with `tsc`, it fails:

```
$ npx tsc
src/types/Mutation.ts:70:13 - error TS2322: Type '{ connect: { id: string | undefined; }; }' is not assignable to type 'UserCreateOneWithoutPostsInput'.
  The types of 'connect.id' are incompatible between these types.
    Type 'string | undefined' is not assignable to type 'number | null | undefined'.
      Type 'string' is not assignable to type 'number | null | undefined'.

70             author: { connect: { id: userId } },
               ~~~~~~

  node_modules/@prisma/client/index.d.ts:2558:3
    2558   author?: UserCreateOneWithoutPostsInput | null
           ~~~~~~
    The expected type comes from property 'author' which is declared here on type 'PostCreateInput'

src/types/Mutation.ts:83:13 - error TS2322: Type 'string | null | undefined' is not assignable to type 'number | null | undefined'.
  Type 'string' is not assignable to type 'number | null | undefined'.

83             id,
               ~~

  node_modules/@prisma/client/index.d.ts:2535:3
    2535   id?: number | null
           ~~
    The expected type comes from property 'id' which is declared here on type 'PostWhereUniqueInput'

src/types/Mutation.ts:95:20 - error TS2322: Type 'string | null | undefined' is not assignable to type 'number | null | undefined'.
  Type 'string' is not assignable to type 'number | null | undefined'.

95           where: { id },
                      ~~

  node_modules/@prisma/client/index.d.ts:2535:3
    2535   id?: number | null
           ~~
    The expected type comes from property 'id' which is declared here on type 'PostWhereUniqueInput'


Found 3 errors.
```

We should:

- [ ] check whether this happens also for other TS examples
- [ ] fix the errors in `typescript/graphql-auth` and any others we find

**Comment by steebchen** [comment]
This also happens in `typescript/graphql-sdl-first`

**Comment by steebchen** [comment]
I think to prevent this in the future for all projects, we should just use `tsc` to transpile Typescript code and call `node dist/server.js` or whatever in the npm script.

**Comment by nikolasburk** [comment]
> This also happens in `typescript/graphql-sdl-first`

Yeah, it probably happens in a most TX examples I could imagine since we never tested for that...

**Comment by steebchen** [comment]
We should fix that ASAP because a lot of users will encounters errors in their IDE as well:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/5013932/75051289-2d80d400-5500-11ea-9c91-b8c2136884a5.png">

**Comment by Smackzter** [comment]
doing `npm run build` also spits out the same errors. I'm new to prisma and nexus, but initially I thought this issue related to different behaviour between tsc and ts-node, but the build script *should* be running ts-node. Are the examples just broken? Would love to get started, but it's a bit difficult with the not-human-friendly errors and the examples not working :)

**Comment by nikolasburk** [comment]
TODOs:

- [ ] script
- [ ] graphql
- [ ] graphql-apollo-server
- [ ] graphql-sdl-first
- [ ] graphql-auth
- [ ] rest-express
- [ ] grpc

**Comment by ngduc** [comment]
I'm getting this issue when building it.
why was this closed?

**Comment by steebchen** [comment]
@ngduc Please open a new issue and describe in which repository this happens exactly. Thanks!
