### ISSUE TITLE
Add NuxtJS example

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-examples#1539]
From our internal notion doc, the devrel team wants to have a NuxtJS example. Since it was initially planned to go into the e2e repo, I already have a template locally so if anyone else than me gets this task assigned, I can provide a basic starter project.

**Comment by mtltechtemp** [comment]
@steebchen
Hello, could you send me the starter project ?
That would help me.

Thanks.

**Comment by steebchen** [comment]
@mtltechtemp For now, you can try the project in https://github.com/prisma/prisma2-e2e-tests/tree/feat/frameworks/nuxtjs – but please note that this may be outdated, and that the nuxtjs team is working on features which improve handling APIs etc.)

**Comment by ruheni** [comment]
There's a Nuxt example in the JavaScript examples. I'll go ahead and close this.
