### ISSUE TITLE
prisma-examples graphql-nextjs error ...

### ISSUE THREAD

**Issue by namiomiru** [prisma/prisma-examples#1545]
error after npm install 
Is there a way to fix this?

![image](https://user-images.githubusercontent.com/34525483/75562186-849c2100-5a8b-11ea-8df4-caab91c2f378.png)
![image](https://user-images.githubusercontent.com/34525483/75562212-8fef4c80-5a8b-11ea-93a9-d1e0d3ffbcc8.png)
![image](https://user-images.githubusercontent.com/34525483/75562259-a3021c80-5a8b-11ea-96a8-28ad3cb2cc6f.png)

**Comment by catalinmiron** [comment]
Add the following to `makeSchema({})`

```ts
typegenAutoConfig: {
    sources: [
      {
        source: '@prisma/client',
        alias: 'client'
      }
    ]
  }
```

```ts
export const schema = makeSchema({
  types: [Query, Mutation, Post, User, GQLDate],
  outputs: {
    typegen: path.join(__dirname, 'nexus-typegen.ts'),
    schema: path.join(__dirname, 'schema.graphql')
  },
  typegenAutoConfig: {
    sources: [
      {
        source: '@prisma/client',
        alias: 'client'
      }
    ]
  }
});
```

**Comment by namiomiru** [comment]
I tried your code but got the same error.
ㅠ.ㅠ

**Comment by catalinmiron** [comment]
@namiomiru you also need to generate the schema after the changes. Could you please try it and let me know if you can still repro the issue. Thanks!

**Comment by namiomiru** [comment]
after change your code

npm  run generate

 "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "generate": "npm -s run generate:prisma && npm -s run generate:nexus",
    "generate:prisma": "prisma2 generate",
    "generate:nexus": "ts-node --transpile-only pages/api",
 },

the same error ㅠ.ㅠ
What can I try more?
Thank you for always reply

**Comment by namiomiru** [comment]
@catalinmiron 

after change your code

npm run generate

"scripts": {
"dev": "next",
"build": "next build",
"start": "next start",
"generate": "npm -s run generate:prisma && npm -s run generate:nexus",
"generate:prisma": "prisma2 generate",
"generate:nexus": "ts-node --transpile-only pages/api",
},

the same error ㅠ.ㅠ
What can I try more?
Thank you for always reply

**Comment by namiomiru** [comment]
@catalinmiron 

Thanks to this I understood and solved it.
There is one more problem. Can you help me?

my code ...

import { idArg, makeSchema, objectType, stringArg, asNexusMethod } from "nexus";
import { GraphQLDate } from "graphql-iso-date";
import { PrismaClient } from "@prisma/client";
import { graphql } from "graphql";
import path from "path";

import { generateToken, generateToken22 } from "../../src/util/generate";
import tencentcloud from "tencentcloud-sdk-nodejs";
import axios from "axios";
import bcrypt from "bcrypt";
export const GQLDate = asNexusMethod(GraphQLDate, "date");

const prisma = new PrismaClient();
const Bill = objectType({
  name: "Bill",
  definition(t) {
    t.string("CashPayAmount");
    t.id("id");
    t.string("name");
    t.string("RealTotalCost");
    t.list.field("SummaryOverview", { type: SummaryOverview });
  }
});
const BillData = objectType({
  name: "BillData",
  definition(t) {
    t.string("CashPayAmount");
    t.string("RealTotalCost");
    t.field("SummaryOverview", {
      type: SummaryOverview,
      list: true
    });
  }
});
const Company = objectType({
  name: "Company",
  definition(t) {
    t.id("id");
    t.string("name");
    t.string("payeruin");
    t.string("secretid");
    t.string("secretkey");
  }
});
const ExchangeRate = objectType({
  name: "ExchangeRate",
  definition(t) {
    t.string("basePrice");
    t.string("change");
    t.string("changePrice");
    t.string("code");
    t.string("country");
    t.string("currencyCode");
    t.string("date");
    t.string("highPrice");
    t.string("lowPrice");
    t.string("name");
    t.string("openingPrice");
    t.string("provider");
    t.string("recurrenceCount");
    t.string("time");
  }
});

const SummaryOverview = objectType({
  name: "SummaryOverview",
  definition(t) {
    t.string("BillMonth");
    t.string("BusinessCode");
    t.string("BusinessCodeName");
    t.string("CashPayAmount");
    t.string("IncentivePayAmount");
    t.string("RealTotalCost");
    t.string("RealTotalCostRatio");
    t.string("VoucherPayAmount");
  }
});
const User = objectType({
  name: "User",
  definition(t) {
    t.id("id");
    t.string("jwttoken");
    t.int("level");
    t.string("name");
    t.string("password");
  }
});

const Query = objectType({
  name: "Query",
  definition(t) {
    t.list.field("company", {
      type: "Company",
      resolve: async () => await prisma.company.findMany()
    });

    t.field("billData", {
      type: "BillData",
      args: {
        name: stringArg({ nullable: false }),
        date: stringArg({ nullable: false })
      },
      resolve: async (_, { name, date }) => {
        /* isAuthenticated(request); */

        const test = [
          {
            BusinessCode: "p_vpn",
            BusinessCodeName: "vpn gateway",
            RealTotalCost: "53.70",
            RealTotalCostRatio: "61.96",
            CashPayAmount: "53.70",
            IncentivePayAmount: "0.00",
            VoucherPayAmount: "0.00",
            BillMonth: "2019-11"
          },
          {
            BusinessCode: "p_vpn",
            BusinessCodeName: "vpn gateway",
            RealTotalCost: "53.70",
            RealTotalCostRatio: "61.96",
            CashPayAmount: "53.70",
            IncentivePayAmount: "0.00",
            VoucherPayAmount: "0.00",
            BillMonth: "2019-11"
          }
        ];

        return {
          RealTotalCost: "123",
          CashPayAmount: "123",
          SummaryOverview: test
        };
      }
    });

  }
});

const Mutation = objectType({
  name: "Mutation",
  definition(t) {
    t.field("registerCompany", {
      type: "Company",
      args: {
        name: stringArg({ nullable: false }),
        secretid: stringArg({ nullable: false }),
        secretkey: stringArg({ nullable: false }),
        payeruin: stringArg({ nullable: false })
      },
      async resolve(_, { name, secretid, secretkey, payeruin }, __) {
        const companyCreate = await prisma.company.create({
          data: {
            name,
            secretid,
            secretkey,
            payeruin
          }
        });

        return companyCreate;
      }
    });

    t.field("registerUser", {
      type: "User",
      args: {
        name: stringArg({ nullable: false }),
        password: stringArg({ nullable: false })
      },
      async resolve(_, { name, password }, __) {
        password = await bcrypt.hash(password, 12);
        const userCreate = await prisma.user.create({
          data: {
            name,
            password
          }
        });

        return userCreate;
      }
    });

    t.string("login", {
      args: {
        name: stringArg({ nullable: false }),
        password: stringArg({ nullable: false })
      },
      async resolve(_, { name, password }) {
        try {
          const user = await prisma.user.findOne({ where: { name } });
          const result = await bcrypt.compare(password, user.password);
          if (result) {
            const token = generateToken(name);
            return token;
          } else {
            return false;
          }
        } catch (error) {
          return false;
        }
      }
    });

    t.string("logUserIn", {
      args: {
        token: stringArg({ nullable: false })
      },
      async resolve(_, { token }, __) {
        return token;
      }
    });
  }
});

export const schema = makeSchema({
  types: [
    Query,
    Mutation,
    User,
    Company,
    SummaryOverview,
    BillData,
    ExchangeRate,
    GQLDate
  ],
  outputs: {
    typegen: path.join(__dirname, "nexus-typegen.ts"),
    schema: path.join(__dirname, "schema.graphql")
  },
  typegenAutoConfig: {
    sources: [
      {
        source: "@prisma/client",
        alias: "client"
      }
    ]
  }
});

export default async (req, res) => {
  const query = req.body.query;
  const variables = req.body.variables;
  const response = await graphql(schema, query, {}, {}, variables);
  return res.end(JSON.stringify(response));
};

![image](https://user-images.githubusercontent.com/34525483/76167759-79907180-61ac-11ea-8fd0-c02c550dbb2a.png)

object array filed error

**Comment by namiomiru** [comment]
@catalinmiron 
this I understood and solved it.

**Comment by arnaudjnn** [comment]
Same error +1

**Comment by schonert** [comment]
Same here +1

**Comment by codingforfoodllc** [comment]
was anyone able to get these errors to go away?  I tried doing yarn generate and i got a syntax error from a fresh install.

**Comment by jeffscottward** [comment]
Same error - GraphQL newby - would help if I could

**Comment by nikolasburk** [comment]
This issue was resolved in a recent update of the example. Please feel free to reopen it if you encounter this issue as a regression again 🙂
