### ISSUE TITLE
 I want to know how to use playground (prisma-examples graphql-nextjs)

### ISSUE THREAD

**Issue by namiomiru** [prisma/prisma-examples#1587]
How can I use playgraound with graphql-nextjs?
I need help

**Comment by nikolasburk** [comment]
Hey @namiomiru 👋 you should be able to access the Playground via `http://localhost:3000/api` as described [here](https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-nextjs#using-the-graphql-api) 🙂

**Comment by rpateld** [comment]
it return error on link like 
`{"errors":[{}]}`

**Comment by janpio** [comment]
New link is https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-nextjs#using-the-graphql-api

**Comment by rpateld** [comment]
This is the link returning error : 
![image](https://user-images.githubusercontent.com/56134077/78946148-f0f93f80-7a8f-11ea-8bf2-eef2f16cfae5.png)

**Comment by rpateld** [comment]
> prisma generate

 ▸    Couldn’t find `prisma.yml` file. Are you in the right directory?

Get in touch if you need help: https://slack.prisma.io
To get more detailed output, run $ export DEBUG="*"
(node:3519) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is 
deprecated

**Comment by janpio** [comment]
That sounds like you have an old version of Prisma installed. Best create an issue at prisma/prisma.
