### ISSUE TITLE
Add `$disconnect()` calls in all examples

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#1621]
Right now we don't explicitly `disconnect()` in any of the examples except for the `script` ones.

**Comment by Gomah** [comment]
@nikolasburk What's the best way to do it?

We currently implemented a middleware to disconnect after the resolve function, is there a better way to do that?

```ts
import { Context } from '../context';

export async function prismaDisconnect(
  resolve,
  root,
  args,
  context: Context,
  info
): Promise<any | never> {
  try {
    const response = await resolve(root, args, context, info);
    await context.prisma.disconnect();
    return response;
  } catch (error) {
    context.log.error(error.stack);
    throw error;
  }
}

export const prismaMiddleware = {
  Query: prismaDisconnect,
  Mutation: prismaDisconnect,
};
```

**Comment by zebapy** [comment]
Is this essential to using prisma in serverless? I am getting way too many connect limit issues when trying to deploy nextjs + api endpoints + prisma
