### ISSUE TITLE
Change the way tests are run

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1653]
Right now there is only 1 test, that loops through all folders. That is practical, because it makes sure that all examples (= folders) have the proper test configuration that then is run during the test - no one can add a test without it also being tested.

Unfortunately that leads to super busy log output and makes it hard to understand what is going on.

An alternative suggestion: The test starts with a script that tests if for all folders there is a Github Actions workflow/job that triggers the .sh file that currently would be triggered via looping through the folders. That way, the whole test run can still be failed if an example is missing.

**Comment by steebchen** [comment]
It's probably a bit tricky to test for if there's a workflow defined for a given file. Definitely possible but we probably need to use a yaml parser to read the workflow files properly and then compare stuff, unless you have a better suggestion.

**Comment by mohe2015** [comment]
@steebchen Depending on how the workflow files should look you could also write a script that loops through the folders and just generates a workflow for them. So no parsing just regenerating the file every time.

**Comment by janpio** [comment]
Couldn't it be easy enough as checking if there is a matching `run.sh` being called via its own job to each folder? Instead of looping through the folders and executing the `run.sh`, it would just make sure there is a job defined that `sh ...run.sh` that file.

**Comment by steebchen** [comment]
(Just to clarify, the script already tests if all projects have a run.sh file, and throws if there's a project without a defined test. It's just doing that in the same single test run.)

So did I understand correctly that you want to have one job ("GitHub check") which makes sure all projects have defined a GH workflow (so that script would read .github/workflows/ yaml files and compare strings etc.), and then a dedicated check for each project? Or do you want to have a single job ("GitHub check") as is but split the steps into 1) making sure all projects have test files defined and 2) one separate step for each project?

**Comment by janpio** [comment]
> So did I understand correctly that you want to have one job ("GitHub check") which makes sure all projects have defined a GH workflow (so that script would read .github/workflows/ yaml files and compare strings etc.), and then a dedicated check for each project? 

Yes, that is probably what I meant (if "Job" and "check" are actually the same thing). Basically this changes the testing setup here from 1 job that checks if all projects have tests first, then runs all of them one after another to 1 job that checks if all projects have a job defined and can fail the build if not, and many individual jobs for all projects.

> Or do you want to have a single job ("GitHub check") as is but split the steps into 1) making sure all projects have test files defined and 2) one separate step for each project?

No, I think just switching over to steps would give not much benefit.
