### ISSUE TITLE
Dummy SQLite DBs in Migrate examples

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#1660]
Currently some examples in the `experimental` directory contain a dummy database called `dev.db` (e.g. [here](https://github.com/prisma/prisma-examples/tree/prisma2/experimental/typescript/script/prisma)). At the same time, the README instructs to get started from scratch with Prisma Migrate commands.

We should fix this in either of these ways:

- remove `dev.db` and have the RADME be the source of truth for the setup
- adjust the README to spare the `migrate` command because the dummy DB is already there

**Comment by ruheni** [comment]
I think this has already been taken care of. I'll go ahead and close the issue.
