### ISSUE TITLE
Where is prisma-generate-schema repository

### ISSUE THREAD

**Issue by brikou** [prisma/prisma-examples#17]
I guess it is not open source yet, but I really wish to check it :pray:

**Comment by divyenduz** [comment]
It is open source but in beta branch at the moment - https://github.com/prisma/prisma/tree/beta/cli/packages/prisma-generate-schema

**Comment by zvictor** [comment]
The link is broken. What has happened to the package?

**Comment by divyenduz** [comment]
The code has moved here https://github.com/prisma/prisma/tree/master/src/packages

and the names might have changed.

**Comment by zvictor** [comment]
it looks like it has been killed, no? I think prisma has moved to a different approach and doesn't use anything similar to prisma-generate-schema anymore.

I am [interested on studying its source code](https://github.com/zvictor/faugra/issues/1#issuecomment-716585761).
Do you know where I can find the code of the old prisma-generate-schema, as it was?

**Comment by divyenduz** [comment]
Aha, now I think I remember what package this refers too. This is from Prisma 1 and that code was moved and can be found here https://github.com/prisma/prisma1/tree/master/cli/packages

It has `prisma-generate-schema` :) 

Curious about `faugra`, I will check it out later.

**Comment by zvictor** [comment]
thank you so much!

`faugra` is brand new and I haven't announced it anywhere yet other than communicating the fauna team.
Any feedback you could give would be extremely appreciated :)
