### ISSUE TITLE
Simplify SDL-first example with graphql-import

### ISSUE THREAD

**Issue by Sevensidedmarble** [prisma/prisma-examples#1717]
Wouldn't it be better to simplify the SDL-first example by using something like https://github.com/ardatan/graphql-import to import the prisma.schema file?

**Comment by nikolasburk** [comment]
Het @Sevensidedmarble 👋 thanks a lot for raising this. Using `graphql-import` to import from `schema.prisma` is not possible because Prisma uses a different modeling language than GraphQL.

Let me know if you have any further questions, happy to help 🙂
