### ISSUE TITLE
Add Nexus CRUD example

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#1747]
We should have an example that shows how to expose a full CRUD API for Prisma models using `t.crud`.

**Comment by darrylyoung** [comment]
Yeah, I think that would be really useful, especially for people starting out.

**Comment by Nhilesh** [comment]
Another great tooling https://paljs.com/ works better, I got the prisma client working less then a minute.
Just a suggestion, Nexus documentation for Prisma 2 kinda sucks

**Comment by koniuszy** [comment]
i believe we don't want to achieve this with the dead nexus-prisma-plugin : https://github.com/graphql-nexus/nexus-plugin-prisma right? afair the recommended way is to use pure nexus

what's the real alternative here? - waiting for the new nexus-prisma integration? https://github.com/prisma/nexus-prisma
the crud feat seems to be far away :/ 

with explicitly pointed stack I will be glad to provide such an example
