### ISSUE TITLE
graphql-nextjs file upload?

### ISSUE THREAD

**Issue by namiomiru** [prisma/prisma-examples#1753]
How to implement file upload in graphql-nextjs(graphql upload)?

**Comment by WillGeller** [comment]
I'm pretty sure that is outside the scope of Prisma, which handles interfacing with the DB. If you are looking for something plug n play try [Google's Firebase Cloud Storage](https://firebase.google.com/products/storage?gclid=CjwKCAjwqJ_1BRBZEiwAv73uwJEsfPDvjgwVr8Vo4kLIWVpGGbrwlhlLJRKWRvyZzmoDflnmlYRJHxoCh28QAvD_BwE), this might be helpful for implementing with NextJs which is React based: https://github.com/fris-fruitig/react-firebase-file-uploader

**Comment by namiomiru** [comment]
* https://www.npmjs.com/package/graphql-upload

can't you upload it this way?

i tried but it doesn't work.

**Comment by namiomiru** [comment]
https://www.npmjs.com/package/graphql-upload
can't you upload it this way?

i tried but it doesn't work.

![image](https://user-images.githubusercontent.com/34525483/80554898-8d688f00-8a09-11ea-8938-5bfe6211c057.png)


![image](https://user-images.githubusercontent.com/34525483/80554912-98232400-8a09-11ea-951e-4909e1b4fe44.png)

![image](https://user-images.githubusercontent.com/34525483/80554916-9f4a3200-8a09-11ea-806a-c2a068ba879f.png)

**Comment by ruheni** [comment]
Hi 👋🏽

Were you able to resolve the issue? I'll go ahead and close it.
