### ISSUE TITLE
[typescript/graphql-nextjs] Nexus generate won't work with `esnext` modules in `tsconfig.json`

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma-examples#1763]
When starting a new project using the [graphql-nextjs example](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-nextjs) as a base, I faced an issue regenerating the Nexus client wouldn’t work, as I was facing `SyntaxError: Cannot use import statement outside a module`.
**I realized that next is changing the `tsconfig.json` modules option to `esnext` (from `commonjs`)** 

Using the following in the [package.json (line 11)](https://github.com/prisma/prisma-examples/blob/master/typescript/graphql-nextjs/package.json#L11) fixes it on my Mac (couldn't check on Windows)
`"generate:nexus": "ts-node --transpile-only --compiler-options='{\"module\":\"CommonJS\"}' pages/api"`

That could be something to flag to Nexus, but I wondered if there wouldn't be a better way?

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue! I came across the same problem a while ago and created issues in the [`nexus/schema`](https://github.com/graphql-nexus/schema/issues/391) and [`next.js`](https://github.com/zeit/next.js/discussions/10780) repos. 

Unfortunately, I'm not yet sure what the best way is to work around this, but some has posted this workaround: https://github.com/graphql-nexus/schema/issues/391#issuecomment-619604636

**Comment by thebiglabasky** [comment]
Looks like you already did all the work :)
Thanks, I'll watch for these. Would it be worth to have the workaround implemented in the example (and documented) until this gets fixed?
Happy to put in a PR if you think it's worth it

**Comment by nikolasburk** [comment]
Oh a PR would be amazing ❤️

If possible, it would also be great to reference this open issue in a comment in both `tsconfig.json`s so that people know why this approach has been taken. (I believe [it should be possible to have comments in `tsconfig.json` files](https://www.reddit.com/r/typescript/comments/8na5vb/tsconfigjson_isnt_strict_json_what_now/))

**Comment by ruheni** [comment]
We've updated the example to use Pothos and GraphQL Yoga. In the meantime, I'll go ahead and close the issue.
