### ISSUE TITLE
getting started example is still pointing to Beta2, not 4.

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1765]
https://github.com/prisma/prisma/issues/2359#issuecomment-625784588
+
https://github.com/prisma/prisma/issues/2359#issuecomment-626718963

**Comment by janpio** [comment]
Can confirm:

```
{
  "name": "script",
  "license": "MIT",
  "devDependencies": {
    "@prisma/cli": "2.0.0-beta.2",
    "ts-node": "8.7.0",
    "typescript": "3.8.3"
  },
  "scripts": {
    "dev": "ts-node ./script.ts"
  },
  "dependencies": {
    "@prisma/client": "2.0.0-beta.2"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}

```

via command `curl https://codeload.github.com/prisma/prisma-examples/tar.gz/starter -o starter.tar.gz && tar -zxvf starter.tar.gz prisma-examples-starter/typescript/starter && move prisma-examples-starter\typescript\starter starter && rmdir /S /Q prisma-examples-starter && del /Q starter.tar.gz`

**Comment by janpio** [comment]
Seems to be a bigger problem: https://github.com/prisma/prisma-examples/search?q=2.0.0-beta.&unscoped_q=2.0.0-beta.

**Comment by webnoob** [comment]
Looks like it might be better to specify the versions as `^2.0.0-beta.2` it'll always use latest beta.

**Comment by janpio** [comment]
Nah, we want to run tests and make _sure_ it works with the explicit version. We have a whole setup (`master` branch for stable versions, `alpha` branch for unstable ones, GitHub Actions workflows to keep everything updated and running) - it was just broken.

Should now be fixed and all be on Beta 4 as it should be.
