### ISSUE TITLE
Re-enable tests for `experimental` examples

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#1772]
The projects in the `experimental` folder should also be included in our automatic tests.

**Comment by steebchen** [comment]
The experimental examples are outdated and have to be refactored from scratch. The projects are not synced with the non-experimental projects and a lot of projects are currently broken. That has to be fixed first, then I'm happy to help setting up the tests, although once refactored it's probably straightforward to clone the existing tests and use them for the experimental projects.

**Comment by ruheni** [comment]
The experimental folder was removed from the project. I'll go ahead and close this issue.
