### ISSUE TITLE
Bump GraphQL version to ^15.x.x

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma-examples#1784]
If it is possible...

**Comment by janpio** [comment]
Unfortunately some tests fail, which is why the automated PR to upgrade this did not just get merged: https://github.com/prisma/prisma-examples/pull/1697

**Comment by Akxe** [comment]
It actually did not find some package... `Error: Cannot find module 'graphql-middleware'` it will require some more effort I guess

**Comment by nikolasburk** [comment]
Hey @Akxe 👋 thanks a lot for raising this! As far as I can see, the `graphql` has been updated to `15.x.x` (e.g. [here](https://github.com/prisma/prisma-examples/blob/master/typescript/graphql/package.json#L16)).
