### ISSUE TITLE
proto file types in grpc example

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/prisma-examples#1789]
https://github.com/prisma/prisma-examples/blob/master/typescript/grpc/service.proto

This is not working for me

```proto
message PostRequest {
  string id = 1;
}
```

Error message

```
{
  where: {
    id: '1'
        ~~~
  }
}
```

Argument id: Got invalid value '1' on prisma.findOnePost. Provided String, expected Int.

Changed to

```proto
message PostRequest {
  int32 id = 1;
}
```

And 

```ts
const id = some number
```

in client/post.ts (line 20)

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @TomasMoskala 🙏 I could reproduce the error and fixed it via this PR: https://github.com/prisma/prisma-examples/pull/1903
