### ISSUE TITLE
GraphQL Playground doesn't work in Next.js + Nexus example

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#1805]
It should be accessible via http://localhost:3000/api as described in the README but it's currently not.

**Comment by gustawdaniel** [comment]
I mentioned about this in 

https://github.com/prisma/prisma-examples/issues/1751

**Comment by Maetes** [comment]
@nikolasburk 
i managed to enable it by switching from classic REST => GraphQL to the micro build of apollo server as follows:

`npm i apollo-server-micro`

within the /api/index.ts (or your endpoint file at all)
```
import { ApolloServer } from 'apollo-server-micro';

export const config = {
  api: {
    bodyParser: false,
  },
};

export default new ApolloServer({ schema }).createHandler({
  path: '/api',
});

//   export default async (req, res) => {
//   const query = req.body.query;
//   const variables = req.body.variables;
//   const response = await graphql(schema, query, {}, {}, variables);
//   return res.end(JSON.stringify(response));
// };
```

note: I kept the old implementation for a better comparison

**Comment by nikolasburk** [comment]
Fixed via https://github.com/prisma/prisma-examples/pull/1872. Also, thanks a lot to @Maetes for the initial PR and the easy approach to expose the Playground with `apollo-server-micro` 🙌
