### ISSUE TITLE
A GraphQL file upload example

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma-examples#1814]
According to [this](https://prisma.slack.com/archives/CA491RJH0/p1591582611375700) user request, it would be great to have a simple file upload example with GraphQL
![image](https://user-images.githubusercontent.com/19697099/84047394-d75d7100-a9c8-11ea-9c8e-438c44abb863.png)

**Comment by ruheni** [comment]
This is out of the scope of the Prisma examples. I'll go ahead and close the issue
