### ISSUE TITLE
Cannot establish connection with Apollo server + client in Android

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/prisma-examples#1842]
Hi I am using prisma-nexus with Apollo server but cannot make it work on a mobile device.
https://github.com/TomasMoskala/angular-apollo-app
The server palyground should be live at http://test-4233.rostiapp.cz/
It works fine on PC browser.
Authentication is not implemented yet. The client app should only show a list of users.
Please help!

**Comment by Maetes** [comment]
Sorry cant reach http://test-4233.rostiapp.cz/. I don't know what u mean by "make it work on a mobile device". I guess we need more input even though I'm not an angular / nexus expert

**Comment by nikolasburk** [comment]
Hey @TomasMoskala, thanks a lot for opening this issue! This problem seems unrelated to using Prisma but rather an issue with connectivity in Apollo Server. I recommend that you open up an issue in the [apollo-server](https://github.com/apollographql/apollo-server) repo instead 🙂
