### ISSUE TITLE
Prisma 2 - @unique directive in schema.prisma does not work as expected - ( mySql + Nexus)

### ISSUE THREAD

**Issue by Nhilesh** [prisma/prisma-examples#1845]
Hi,

I've recently started using Prisma 2 after a long wait and very much pleased with its release.
It is fair to have some of the things not work as expected and I would like to let the community know that **@unique** directive in schema.prisma does not work as expected (at least with mySql).

I tried with the prisma examples and everything looked promising 
Then I started playing around the models and noted that the email was meant to be unique.

> // test models
> model User {
>  id        Int       @default(autoincrement()) @id
>  createdAt DateTime  @default(now())
>  email     String    @unique
>  name      String?
>  password  String
>..... 
> }

While running further with the example, I was able to create a ditto same user with duplicate e-mail id on my local MySql instance. 

![Capture](https://user-images.githubusercontent.com/66257640/86535064-38f6f980-befb-11ea-8dc0-ae01b492e952.PNG)

Please have this issue fixed.
FYI, I am using prisma nexus example.

Thanks.
Nhilesh Baua

**Comment by janpio** [comment]
How did you create your database?
What does your database schema (SQL) look like?

**Comment by Nhilesh** [comment]
> How did you create your database?
> What does your database schema (SQL) look like?

Oh boy, somehow, my constraints on every table does not appear unless it is primary column, I am using DB forge to create the tables. I guess I will have to update it to latest version. I dropped the table and recreated the constraint, it worked as expected. Thanks for your prompt reply and suggesting the correct thing.
