### ISSUE TITLE
Change Github Token to be from Prismo

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1846]
Currently automated commits seems to be from @steebchen:

![image](https://user-images.githubusercontent.com/183673/86602489-f983e800-bfa2-11ea-8987-f875ab518033.png)

**Comment by steebchen** [comment]
I am pretty sure that this is just GitHub Actions showing wrong information. There's no token from Prismo or anything, it just uses their email address and GitHub matches that to the respective GitHub account.

**Comment by janpio** [comment]
Hm, true - the commit is from the bot and GH actions still shows you:

![image](https://user-images.githubusercontent.com/183673/86621772-10d0ce80-bfbf-11ea-84a5-bd6753e9a9c6.png)

https://github.com/prisma/prisma-examples/commit/a5b8e80fa6d85ada3c672d768cfb839e7f0b110b
![image](https://user-images.githubusercontent.com/183673/86621804-1f1eea80-bfbf-11ea-9936-6e649c29db3d.png)

Why the connection to _you_ then?

**Comment by steebchen** [comment]
I encountered this previously, it seems that sometimes GH shows the last contributor or something instead of the actual contributor, but I don't really remember why or how it happened. So it could be just as well any other contributor, not just me.

**Comment by steebchen** [comment]
I think I know why this happens! It seems GitHub remembers who creates branches:

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/5013932/86886550-560d1180-c121-11ea-86af-0f2b0bf42354.png">

The script can't create branches at this time, but we could change that.
