### ISSUE TITLE
How to define the port for GraphQL server?

### ISSUE THREAD

**Issue by felinto-dev** [prisma/prisma-examples#1865]
https://github.com/prisma/prisma-examples/blob/master/typescript/graphql-auth/src/server.ts

How can I define what port my GraphQL server will use?

**Comment by Maetes** [comment]
`start(options: Options, callback: ((options: Options) => void) = (() => null)): Promise<void>`

Once your GraphQLServer is instantiated, you can call the start method on it. It takes two arguments: options, the options object defined above, and callback, a function that's invoked right before the server is started. As an example, the callback can be used to print information that the server has started.

Simply write the following and you should be good to go ✌️:

```
const options = {
 port: 1337
}

new GraphQLServer({
  schema,
  context: createContext,
  middlewares: [permissions],
}).start((options, {port}) =>
  console.log(
    `🚀 Server ready at: http://localhost:${port}\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#using-the-graphql-api`,
  ),
)
```
