### ISSUE TITLE
No code in graphql-typegraphql example

### ISSUE THREAD

**Issue by jsplate** [prisma/prisma-examples#1868]
After cloning the whole prisma-examples via https (clone git does not work for me, same as in #1785)  there is no code in the cloned directory, only a README.md.

So npm install does not work because there is nothing to install.

Is this on purpose to only have a description or should there be a project with the code?

**Comment by Maetes** [comment]
Did it once you rose the issue. I'm good to go. Please use the following link to clone and try again:
`https://github.com/prisma/prisma-examples.git`

**Comment by jsplate** [comment]
@Maetes graphql-typegraphql has still only a README.md and no other files. What content do you have in that directory?

**Comment by Maetes** [comment]
@jsplate i'm sorry you are totally right. Didn't recognize that you mean that specific example rather than the dir at all. 

Maybe you are good to go with the examples from typegraphql itself? https://github.com/MichalLytek/type-graphql/tree/prisma/examples

**Comment by jsplate** [comment]
@Maetes Thank you for giving me that hint. I will have a look at that. Nevertheless the empty example is inconvenient. Took time for users to find out that the README.md is wrong...

**Comment by nikolasburk** [comment]
Hey folks 🙌  thanks a lot for raising this! This has been on our TODO list for a while and I finally got around merging a PR: https://github.com/prisma/prisma-examples/pull/1889 Feel free to try it out and share your feedback 🙂

**Comment by jsplate** [comment]
@nikolasburk Thank you very much for the work at the example!
The example works very well as expected.

I found one slight problem: 
The console output of npm run dev is:

�🚀 Server ready at: http://localhost:40
⭐️

It should be 4000 (where it is found as expected). I don't know why this is output is so strange because in the source code it is correct. It seems because of the "rocket" in the console.log. If I remove this it shows the correct port number...
