### ISSUE TITLE
nexus-plugin-prisma upgrade workflow doesn't work with postinstall hook

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-examples#1895]

**Comment by janpio** [comment]
I would say: It runs the `yarn add` with a version of the dependencies, that fails in combination with Prisma CLient in the hook.
Because of that, the updated code is never copied over (which would bring fixed non prisma dependencies)

**Comment by janpio** [comment]
internal thread with links to failing test etc: https://prisma-company.slack.com/archives/CUH6B8FUJ/p1595511451004300

**Comment by ruheni** [comment]
We've updated the GraphQL examples to the latest versions of the packages and none of them are currently using  `nexus-plugin-prisma`. Going ahead and closing the issue.
