### ISSUE TITLE
Unify workflows with e2e-tests

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-examples#1896]
Currently, examples use different workflows than e2e-tests. We should probably re-use them.

**Comment by janpio** [comment]
One difference:
- `e2e-tests` has the run.sh and test.sh in the proejct itself, here it lives in a subfolder of `.github`  - should be easy to unify though

**Comment by divyenduz** [comment]
Replaced with an internal issue that tackles both internal and external CI systems https://github.com/prisma/centeralize-ci/issues/1
