### ISSUE TITLE
javascript/apollo-graph-ql docs error

### ISSUE THREAD

**Issue by warmSnowyMorning** [prisma/prisma-examples#1922]
it says that there is dummy data in "./prisma/dev.db."

however, such is not the case.  pls help

**Comment by janpio** [comment]
Which project exactly?

Per your description I would guess this: https://github.com/prisma/prisma-examples/blob/master/javascript/graphql-apollo-server/prisma/dev.db

**Comment by warmSnowyMorning** [comment]
ah my bad, i'm a beginner.  the file didn't show any contents on github so i thought maybe it was left empty

**Comment by janpio** [comment]
Ah no, it is a binary file that Github just can not display. You need to use a SQLite database UI to look inside it - or run `prisma studio --experimental` to do the same via Prisma Studio.
