### ISSUE TITLE
Schema in the "prisma-examples/experimental/typescript/graphql" example seems to contain an error

### ISSUE THREAD

**Issue by AdamCooman** [prisma/prisma-examples#1931]
I was trying to run the "prisma-examples/experimental/typescript/graphql" example and the schema is complaining about a reference that is wrong.

The definition for Post in the current schema is as follows:
``` prisma
model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?
}
```
Vscode indicates an error here on the author reference. 
I managed to fix it by replacing Post with the following:
``` prisma
model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User? @relation(fields: [authorId], references:[id])
  authorId Int?
}
```

**Comment by janpio** [comment]
That is indeed a broken schema that should be fixed:
https://github.com/prisma/prisma-examples/blob/f327b2939c05449d19a67da6af812246662c5844/experimental/typescript/graphql/prisma/schema.prisma#L10-L16

**Comment by ruheni** [comment]
I've update the Prisma schema. Kindly let me know if you experience any issues.
However, kindly note that the examples in `experimental` are currently not being maintained.
If you'd like up to date examples, kindly check out the `typescript` and `javascript` examples 🙂
