### ISSUE TITLE
Zeit Now README is probably not needed any more

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1935]
https://github.com/prisma/prisma-examples/blob/master/.github/readmes/deployment-platforms/zeit-now/README.md

**Comment by 2color** [comment]
Why is that?

**Comment by janpio** [comment]
Because Zeit has been renamed to Vercel, and we also renamed our example. So next to a README the folder is empty: https://github.com/prisma/prisma-examples/tree/master/deployment-platforms/zeit-now (becaues this template still exists and is probably recreated automatically).
