### ISSUE TITLE
About Fullstack Example with Next.js

### ISSUE THREAD

**Issue by jnthnk** [prisma/prisma-examples#1950]
Maybe this is a stupid question.

**But the REST API example in typescript + prisma + next, would work all inside the same next app?**

Also, this can be deploy all to Vercel free account?

Thanks

**Comment by alfieqashwa** [comment]
Yes, if you're using sqlite, then all you need is just deploy on Vercel. But if you're using posgresql, you can use heroku, or digital ocean for deploy the database (backend) and deploy to Vercel for the frontend. #cmiiw

**Comment by jnthnk** [comment]
I was trying prisma API in Vercel and gives error. This error didn't happen in localhost.
Maybe I have to test it more. Thanks.
