### ISSUE TITLE
GitHub Actions workflows used by this repository might get enabled for the users who published a new fork of this in their own account

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-examples#1988]
See https://github.com/prisma/prisma/issues/3539

If someone publishes this repository in their own account in a new repository, GitHub actions will be enabled for them by default. That will enable the job which updates the dependencies of this repository. This can exhaust the free limit which GitHub has on action for private repos (2000minutes/month)

We will need to figure out how we can prevent this.

**Comment by janpio** [comment]
Suggestion from GH staff: https://github.com/prisma/prisma/issues/3539#issuecomment-689104691

> One option might be to put a condition on each job if: github.owner == prisma which would at least prevent the jobs for actually running on a VM for repos outside the prisma org.
