### ISSUE TITLE
Update outdated instructions (or remove them)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#2008]
Many READMEs still refer to old documentation and repository names.

For example: https://github.com/prisma/prisma-examples/blob/496ab21dc28ae13dc3bcb2494c664a92fa4a2668/.github/readmes/experimental/_next-steps.md#L8
But also non experimental stuff.

**Comment by ruheni** [comment]
I think we can delete the experimental READMEs since the experimental examples were deleted and close this issue. 🤔
