### ISSUE TITLE
Error in node-graphql-auth example

### ISSUE THREAD

**Issue by wontwon** [prisma/prisma-examples#202]
# Issue
 - Followed the steps to get node-graphql-auth up and running, but upon trying to do mutation signUp, I get the following error: 

```
dyld: lazy symbol binding failed: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: /Users/TD/Documents/Projects/GraphQl/prisma-examples/node-graphql-auth/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: /Users/TD/Documents/Projects/GraphQl/prisma-examples/node-graphql-auth/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace
```

**Comment by nikolasburk** [comment]
Hey @wontwon, this should have been solved by the latest refactoring and cleanup effort of the examples. Please try the example again by following the steps in the README. If you're still running into the same problem, please reopen this issue! 🙏
