### ISSUE TITLE
`@prisma` deps should only be updated if tests succeed

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#2063]
Right now, the sync script that updates the `@prisma` dependencies in all example projects always runs upon new releases of Prisma. 

We often had the situation (and are experiencing it right now again as of the latest 2.8.0 release), that changes in the DMMF are breaking the `nexus-prisma` package which is used in a number of examples. Whenever this happens, the examples don't work any more and the tests for them start failing,

Functional example projects are really important for us, so we should make sure that our sync script only updates Prisma dependencies if the tests for a project succeed.

**Comment by divyenduz** [comment]
Reverted this via https://github.com/prisma/prisma-examples/commit/d8bfae33c8f88f971c67126b8c561530b42b32af

This approach brings back a lot of issues like https://github.com/prisma/prisma-examples/issues/2171
I will think of a better way to solve this.

**Comment by divyenduz** [comment]
Synced with @nikolasburk on this, we only want this for the "latest" branch. Proposed solution: 

- Disable `latest` bumping and merging in our update script
- Rely on `renovate` to create a PR for Prisma packages on `major`, do not merge them automatically

It is possible `renovate` is slow for our requirements, so later, we can build this tooling to create PRs in our script if needed.

**Comment by nikolasburk** [comment]
Sounds good to me! 

Also, to make the tradeoff here explicit: It's much more important for the examples to be working/functional rather than all dependencies always and immediately being up to date. 

So we should favour solutions where we can ensure that updated dependencies don't break anything over solutions that update dependencies quickly/automatically but might break things.

**Comment by divyenduz** [comment]
The current behaviour is different then specified by https://github.com/prisma/prisma-examples/issues/2063#issuecomment-719458188

We configured renovate to merge automatically when tests are green. 

Internal discussion: https://prisma-company.slack.com/archives/CFRDLGR8W/p1608290949007900
