### ISSUE TITLE
[typescript/apollo-graphql-server]: Some mutations are removed from schema

### ISSUE THREAD

**Issue by benrozsa** [prisma/prisma-examples#2077]
#### Steps to reproduce 
- npm install
- npm run dev
- Open loclahost:4000/graphql
- Only createDraft and and publish mutations are available

Some other methods were defined in the Mutations section, although not as fields.  
```js
t.crud.createOneUser({ alias: 'signupUser' })
t.crud.deleteOnePost()
```

#### It may not be a bug, but how can I access signup?

HEAD: 
commit 0eb8f834db6df916a4668405d9d76d6a2b136096 (grafted, HEAD -> latest, origin/latest, origin/HEAD)
Author: Renovate Bot <bot@renovateapp.com>
Date:   Tue Oct 6 01:52:47 2020 +0000

chore(deps): update dependency @types/node to v14.11.4

**Comment by ruheni** [comment]
Hey @robence! 
Could you kindly share more information such the versions of the packages you're running  and screenshots of the error you're running into 🙃

**Comment by benrozsa** [comment]
Hi @ruheni!
After doing a clean install, it seems to work now: 

git clone git@github.com:prisma/prisma-examples.git --depth=1
cd prisma-examples/typescript/graphql-apollo-server
npm install
npm run dev

After running npm run dev:
![image](https://user-images.githubusercontent.com/20738129/100475500-8ca0f400-30e3-11eb-89e3-a0a29181e9c9.png)


Current dependencies:
    "@nexus/schema": "0.19.1",
    "@prisma/cli": "2.12.1",
    "@prisma/client": "2.12.1",
    "@types/node-fetch": "2.5.7",
    "apollo-server": "2.19.0",
    "graphql": "15.4.0",
    "nexus-plugin-prisma": "0.25.0

I think this issue is resolved, thanks
