### ISSUE TITLE
node-graphql-auth 'signup' mutation

### ISSUE THREAD

**Issue by pierpontleather** [prisma/prisma-examples#21]
Signup mutation doesn't work with example in the readme. User will receive error in the Playground because 'name' is a required field. 

Two possible solutions: 

1. Change the schema.graphql file's 'User' definition to be: 
```
type User {  
  id: ID!  
  email: String!  
  name: String  
}
```

-- OR --

2. Change the README.md example mutation of 'signup' to include a name argument. 
```
mutation {
  signup(name: "Alice" email: "alice@prisma.io", password: "graphql") {
    token
  }
}
```

**Comment by abhiaiyer91** [comment]
@pierpontleather Thanks for filing! Resolved in https://github.com/prisma/prisma-examples/pull/25
