### ISSUE TITLE
Make workflow names better

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-examples#2181]
Test matrix was implemented in https://github.com/prisma/prisma-examples/pull/2180

However, job names are "path-like" and not easily readable. This issue tracks fixing them. 

![image](https://user-images.githubusercontent.com/746482/97558327-41a89980-19dc-11eb-8675-d3a0e4286bf3.png)

**Comment by janpio** [comment]
From conversation: Goal is to have `test(typescript/test-nextjs)` in this list
