### ISSUE TITLE
rest-nextjs doesn't exist anymore

### ISSUE THREAD

**Issue by FredericEspiau** [prisma/prisma-examples#2183]
This repo doesn't exist anymore: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs

It is referenced in several documents: https://github.com/search?q=org%3Aprisma+rest-nextjs&type=code

**Comment by nikolasburk** [comment]
Hey @FredericEspiau, thanks a lot for catching this! The example has indeed been renamed and now lives here: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes

It would be awesome if you could maybe spend a few minutes yourself and create a PR to help us fix this. If not no problem and we'll try to fix it ourselves as soon as possible. (Also note that only the `typescript/rest-nextjs` example has been renamed, the `javascript/rest-nextjs` still exists).

In any case, thanks for your help! 🙌

**Comment by FredericEspiau** [comment]
@nikolasburk this is done:
https://github.com/prisma/docs/pull/966
https://github.com/prisma/prisma-examples/pull/2186
