### ISSUE TITLE
Clarifying array support?

### ISSUE THREAD

**Issue by kleydon** [prisma/prisma-examples#2204]
The documentation's [database features matrix](https://www.prisma.io/docs/reference/database-reference/database-features#misc), suggests that arrays are _not_ supported in SQLite, however the [graphql-auth example](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-auth)'s [schema.prisma file](https://github.com/prisma/prisma-examples/blob/latest/typescript/graphql-auth/prisma/schema.prisma) contains a `Post[]` array reference (in the `User` model), and is relying on an SQLite database (dev.db).

What's going on? Can you clarify either the documentation, or the example?

Thanks.

**Comment by nikolasburk** [comment]
Hey @kleydon, thanks for opening this issue!

This is correct, SQLite does not support arrays. However, the example you're mentioning doesn't use an array _in SQLite_ but it creates an abstraction for a 1-n relation in the Prisma schema – so the array doesn't exist in the DB but only on the Prisma-level.

I recommend reading the [relations](https://www.prisma.io/docs/concepts/components/prisma-schema/relations) page for a bit more context on this 🙂
