### ISSUE TITLE
typescript/graphql-apollo-server: npm install fails

### ISSUE THREAD

**Issue by npetronikolos** [prisma/prisma-examples#2232]
when i install dep i receive the foll

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: typescript-graphql@undefined
npm ERR! Found: @nexus/schema@0.18.0
npm ERR! node_modules/@nexus/schema
npm ERR!   @nexus/schema@"0.18.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nexus/schema@"^0.15.0 || ^0.16.0 || ^0.17.0" from nexus-plugin-prisma@0.23.1
npm ERR! node_modules/nexus-plugin-prisma
npm ERR!   nexus-plugin-prisma@"0.23.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by janpio** [comment]
In which project are you trying to run `npm install` (I assume)?

**Comment by npetronikolos** [comment]
https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-apollo-server

**Comment by ruheni** [comment]
Could you try deleting the `node_modules` folder, upgrading to the latest versions of the dependencies and running `npm install` again

**Comment by npetronikolos** [comment]
Thank you I have done that already. There was an update in the rep  that I did a day ago.

**Comment by ruheni** [comment]
Are you still experiencing the error?

**Comment by npetronikolos** [comment]
No
