### ISSUE TITLE
Remove `nexus-plugin-prisma` from `graphql-auth` examples

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#2261]
Right now there are compatibility issues of graphql-middleware and the nexus-plugin-prisma. Since graphql-middleware is currently not maintained, we can resolve this by removing the nexus-plugin-prisma dep from these examples.

**Comment by janpio** [comment]
Note internal discussion at https://prisma-company.slack.com/archives/C8AKVD5HU/p1606326022019600?thread_ts=1605093353.018800&cid=C8AKVD5HU

**Comment by ruheni** [comment]
Hey @janpio 👋🏾
Kindly check out https://github.com/prisma/prisma-examples/tree/migrate-apollo/typescript/graphql-auth and let me know if you run into any issues/errors. 🙃

**Comment by janpio** [comment]
That has worked, no no need to remove `nexus-plugin-prisma` 👍 
Thanks @ruheni
