### ISSUE TITLE
Authorization Header not working

### ISSUE THREAD

**Issue by mattinannt** [prisma/prisma-examples#2295]
Hi,
I'm trying to get the typescript/graphql-auth example running, but getting stuck on authorising a request using the Authorization-Header. I get the graqphQL response `"Not Authorised!"` and my code seems to fail in function `getUserId` (utils.ts) at command ```const Authorization = context.request.get('Authorization')``` with the error `Cannot read property 'get' of undefined`.
In the `experimental/typescript/graphql-auth` example with graphql-yoga this seems to work. But in normal typescript/javascript example I have no success :-(

**Comment by ruheni** [comment]
Hi @mnannt 👋🏾
I'm sorry you're experiencing the issue 😢. We're working on the example and we'll keep you updated 😉
