### ISSUE TITLE
go-script import path error

### ISSUE THREAD

**Issue by gedw99** [prisma/prisma-examples#232]
problem is here: 
https://github.com/prisma/prisma-examples/blob/master/go-script/main.go#L5

````
cd /Users/apple/workspace/go/src/github.com/prisma/prisma-examples/go-script && go get ./...
package go-gin/prisma-client: unrecognized import path "go-gin/prisma-client" (import path does not begin with hostname)
make: *** [dep-more] Error 1
````

I think you should have the full path

**Comment by gedw99** [comment]
doing same problem here: https://github.com/prisma/prisma-examples/blob/master/go-gin/main.go#L4

````
cd /Users/apple/workspace/go/src/github.com/prisma/prisma-examples/go-gin && go get ./...
package go-gin/prisma-client: unrecognized import path "go-gin/prisma-client" (import path does not begin with hostname)
make: *** [run-gogin-client] Error 1
````

**Comment by nikolasburk** [comment]
Hey @gedw99, this should have been solved by the latest refactoring and cleanup effort of the examples. Please try the example again by following the steps in the README. If you're still running into the same problem, please reopen this issue! 🙏
