### ISSUE TITLE
prisma client missing in resolver

### ISSUE THREAD

**Issue by jdevng** [prisma/prisma-examples#2402]
I'm attempting to write the prisma database from the resolver, but it doesn't seem to pass through the context function. Is it possible that the PrismaClient isn't binded? Is there prisma support packages like auth0?

```
const prisma_db = new PrismaClient()
//server
const server = new ApolloServer({
gateway,
context: ({ req }) => {
const user = req.user || null;
console.log("Prisma: " + prisma_db);
return { user: user, db: prisma_db};
}
})
//resolver
viewer(parent, args, context, info) {
console.log("user: " + context.user)
console.log("db: " + context.db)
//output
[dev:gateway] Prisma: [object NewPrismaClient]
[dev:accounts] user: [object Object]
[dev:accounts] db: undefined

**Comment by nikolasburk** [comment]
Hey @jdevng, can you elaborate which example you're referring to? I don't see any examples that are using a `gateway` object with Apollo Server?

However, generally your code to attach the `PrismaClient` instance to the resolver seems fine to me. Can you maybe share a reproduction of your problem?

**Comment by jdevng** [comment]
We just figured it out - in a remote service, the context isn't inherited from the gateway. Not really a prisma issue.

**Comment by nikolasburk** [comment]
Great to hear 🙌  I'll close the issue then, let me know if you want to reopen it (or when you run into other issues in the future 🙂 ).
