### ISSUE TITLE
N+1 problem for nestjs-graphql example

### ISSUE THREAD

**Issue by sahildeliwala** [prisma/prisma-examples#2464]
Facing n+1 problem with [typescript/nestjs-graphql](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nestjs) example

Node Version: v14.15.3
NPM Version: 6.14.9

```
query {
  filterPosts(searchString:"") {
    id
    author {
      id
      email
    }
  }
}
```

![image](https://user-images.githubusercontent.com/10909011/106382724-79fab200-63e7-11eb-82fd-258866632837.png)

**Comment by nikolasburk** [comment]
Thanks so much for reporting this @sahildeliwala, this has recently been resolved via this issue: https://github.com/prisma/prisma/issues/5274

**Comment by Adrinalin4ik** [comment]
You can try to use this library [https://github.com/Adrinalin4ik/Nestjs-Graphql-Tools][1] it allows to overcome n+1 with the simple decorator. And it has minimum deps.


  [1]: https://github.com/Adrinalin4ik/Nestjs-Graphql-Tools
