### ISSUE TITLE
Adjust tests

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#2665]
Currently tests are using `yarn prisma db push --preview-feature` (e.g. [here](https://github.com/prisma/prisma-examples/blob/latest/.github/tests/typescript/graphql/run.sh#L6)) for the initial setup.

They should instead use the same insturctions from the READMEs for setup to ensure there are no issues:

```
npx prisma migrate dev --name init
npx prisma db seed --preview-feature
```

Note also that the tests are currently using Yarn instead of npm, unless there's a reason to keep Yarn we should switch to npm here as well for consistency.

**Comment by janpio** [comment]
> Note also that the tests are currently using Yarn instead of npm, unless there's a reason to keep Yarn we should switch to npm here as well for consistency.

The whole "keep a `dev` branch updated with newest version" system uses Yarn as well - that might have an influence here.

**Comment by ruheni** [comment]
The tests have been updated to use `prisma migrate dev` and the package manager specified in the script instead of yarn. 🙂

Going ahead and closing the issue in the meantime.
