### ISSUE TITLE
Expand tests

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#2666]
The tests per example should 1-1 mirror the instructions from the README (incl all sample queries/requests and instructions from the "Evolving the app"-section) to make sure the entire example is fully functional and doesn't produce any errors. 

We probably want to integrate a testing framework instead of writing all tests in bash.

**Comment by janpio** [comment]
Note that the shell scripts are the entry points of the CI testing setup in this repository. It is perfectly fine to place the testing logic somewhere else of course (having fully tested examples is awesome!), but the test execution still needs to be triggered via the existing `run.sh` shell scripts right now for that to work.
