### ISSUE TITLE
Unknown arg `viewCount` in data.posts.create.0.viewCount

### ISSUE THREAD

**Issue by marcusvpires** [prisma/prisma-examples#2672]
Hi, I think you forgot put viewCount in prisma / schema.prisma > Post, when I migrate table with "view Count Int?" the error stopped, I think it's just this, one minute can correct!

**Comment by ruheni** [comment]
Hi @M4rcusVinicius  👋🏾

Thank you for spotting this. Could you provide a little more context on what example is missing the `viewCount` field in the schema?

In the meantime, we are revamping the examples as well #2667 (REST, gRPC, and full-stack examples).
