### ISSUE TITLE
Error while running example: parameter 'req' implicitly has an 'any' type

### ISSUE THREAD

**Issue by pavanagrawal123** [prisma/prisma-examples#268]
https://github.com/prisma/prisma-examples/blob/7539c7f3a46b7fddf1a2f89f1ed6075a47e4145a/typescript-graphql-auth/src/index.ts#L8

Typescript is complaining here with: `parameter 'req' implicitly has an 'any' type`

Could fix with an ignore in the `tsconfig.js` like this: `"noImplicitAny": false,`, but I am not a typescript expert in any way shape or form ¯\\\_(ツ)\_/¯

**Comment by nikolasburk** [comment]
Hey @pavanagrawal123, this should have been solved by the latest refactoring and cleanup effort of the examples. Please try the example again by following the steps in the README. If you're still running into the same problem, please reopen this issue! 🙏
