### ISSUE TITLE
Use `graphql-scalars` instead of `graphql-iso-date` as its maintained

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma-examples#2699]
While installing `graphql-iso-date`, I got the following error:

```ts
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: node-graphql@1.0.0
npm ERR! Found: graphql@15.5.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^15.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-iso-date@3.6.1
npm ERR! node_modules/graphql-iso-date
npm ERR!   graphql-iso-date@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I also needed to install `@types/graphql-iso-date`

Instead, use `graphql-scalars` in the examples as its maintained. It's the same thing.

I found it in this example but I'm pretty sure it must be used in most projects:

https://github.com/prisma/prisma-examples/blob/de385bc5ac1d1edb0f143b444d845927e367feaa/typescript/graphql/package.json#L17

See the Github's search → https://github.com/prisma/prisma-examples/search?q=graphql-iso-date

**Comment by ruheni** [comment]
Thank you for creating this issue. We'll look into this. 🙂
