### ISSUE TITLE
Dummy DB data appears to be MIA

### ISSUE THREAD

**Issue by zackdotcomputer** [prisma/prisma-examples#2705]
Folowing the instructions for [this example](https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes-auth) yields an empty dev.db file. Clicking the link from the README leads to a Github 404. I'm guessing the data has somehow gone wandering?

**Comment by janpio** [comment]
cc @ruheni, I think you reworked that in https://github.com/prisma/prisma-examples/pull/2624

**Comment by ruheni** [comment]
> cc @ruheni, I think you reworked that in #2624

I did not modify the full-stack examples. I'll look into this. 🙂

**Comment by zackdotcomputer** [comment]
Aha! Yup #2624 rm's the db for this example (`rest-nextjs-api-routes-auth`) but doesn't provide the same "how to seed" update to the README that other examples got. Probably an unintended side effect of adding a blanket .gitignore of `dev.db` at the [package root here](https://github.com/prisma/prisma-examples/commit/e69ea94e554bba5297b6472ba791498fe6e82ad8#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947)?

**Comment by esemeniuc** [comment]
Running into the same issue, no `dev.db` files

**Comment by esemeniuc** [comment]
You can find the files here: https://github.com/prisma/prisma-examples/blob/4e9e10699ce61eae23089dc2ce9a81f9a67a251e/typescript/rest-nextjs-api-routes-auth/prisma/dev.db

**Comment by zackdotcomputer** [comment]
Yeah... not sure why this isn't fixed yet. Seems like plan would be to revert #2624's delete of the not-seeded db files and rename them to something like `static-dev.db` that wouldn't get caught by the gitignore?

**Comment by esemeniuc** [comment]
Another solution is to generate the schema using `prisma migrate dev --name init` or `prisma migrate reset`, although I haven't tried this on the example yet

**Comment by zackdotcomputer** [comment]
@esemeniuc the schema isn't the issue - it does generate fine. It's that the other databases are seeded with dummy data which makes them easier to get started with - that is what is missing from this example because of this deletion.

**Comment by esemeniuc** [comment]
ah thats true, i forgot that this example doesn't include a `seed.ts`

**Comment by ruheni** [comment]
Hello friends 👋🏾

This issue should be fixed now. I've updated the example: added `prisma/seed.ts` file and updated the README instructions.

Thank you for your patience. Let me know if you encounter any further issues. 🙂
