### ISSUE TITLE
react-apollo project is deprecated in favor of @apollo/client

### ISSUE THREAD

**Issue by zackdotcomputer** [prisma/prisma-examples#2719]
Per the note on https://github.com/apollographql/react-apollo#readme

This is starting to cause issues because of the new npm stricter dependency checking.

Sorry for brusqueness of this initial report - it's late and wanted to jot this down before forgetting about it. Ran into this while exploring the [graphql + next example](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nextjs).

**Comment by janpio** [comment]
Yep, that should fortunately be the only affected example project: https://github.com/prisma/prisma-examples/search?q=react-apollo

**Comment by zackdotcomputer** [comment]
Opened a PR to update the dependencies in that example and clarify the client.js file into a slightly easier to understand (though less automatic) two-function system based on Next's example.

**Comment by koniuszy** [comment]
@ruheni 
I believe we can close it now 👌 

ref: https://github.com/prisma/prisma-examples/pull/3033
