### ISSUE TITLE
Is there any way to avoid defining the schema in two distinct locations?

### ISSUE THREAD

**Issue by jcuffe** [prisma/prisma-examples#2841]
Hey Prisma team! I'm exploring GraphQL solutions, and I noticed that this example has the entire schema defined in two places.

I'm looking for a solution that allows me to define my schema one time, so that future modifications to the schema do not have to be examined for consistency. Is this possible, or on the road map? It seems like the schema defined in `schema.prisma` should contain enough information to run the server - am I missing some crucial information?

**Comment by kingfishx23** [comment]
Im curious about this. is there any resource to find the answer?

**Comment by jcuffe** [comment]
@kingfishx23 The best solution I was able to find was the code-first implementation. By defining all types and scalars in code, the schema can be inferred/generated and updates can be made in one location. Not ideal, but workable!
