### ISSUE TITLE
How to read from firebase functions config inside schema.prisma

### ISSUE THREAD

**Issue by rajapattanayak** [prisma/prisma-examples#2894]
Hi

How can I  read the env variables, that I set in the firebase cloud function, inside schema.prisma file? I don't want to hard code the database URL. I can not import the firebase functions either.

Example:
import * as functions from "firebase-functions";
export const DB_CONNECTION_URL = functions.config().backend.db_connection_url

datasource db {
  provider = "mysql"
  url      =  DB_CONNECTION_URL
}

How can I achieve this?

Thanks

**Comment by janpio** [comment]
You would need to write that into an environment variable (or `.env` file), and then use `env()` in the schema to access that: https://www.prisma.io/docs/concepts/components/prisma-schema#using-environment-variables

**Comment by rajapattanayak** [comment]
Thanks, @janpio. It worked.  I followed the following steps to connect to cloud SQL from firebase

1. created .env file in root with the content below
database.url = 'mysql://user:password@localhost/db?socket=/cloudsql/project-id:region:cloud-sql-instance'

2. schema.prisma
datasource db {
  provider = "mysql"
  url = env("database.url")
}

3. Set the env variable in firebase with the  following command
firebase functions:config:set databse.url="mysql://user:password@localhost/db?socket=/cloudsql/project-id:region:cloud-sql-instance"

4. Added "npx prisma generate" in predeploy

5. deploy the config and Prisma client
firebase deploy --only functions

Now when I access the endpoint I can connect to MySQL to get data.

Note:
I still find some issues when I change the URL to connect other MySQL instance the Prisma client inside node_modules are not picking up the change so firebase still points to the old database. Even though I added "npx prisma generate" in pre-deploy script. I am deleting the cloud function from firebase and deploying again to pick the change which is not the best solution. if anyone can help me with this.

**Comment by janpio** [comment]
Hm, if you are using the `env()` syntax in your schema the connection string is _never_ written down in the Client. It is always read from the environment variable, so I think something is going wrong with updating that one. Did you maybe commit the `.env` file and it is used permanently? I am not sure if the `.env` file overwrites the env var, or the other way around.

If you can not fix this rpoblem, please open an issue at https://github.com/prisma/prisma
