### ISSUE TITLE
Flexibility to auth

### ISSUE THREAD

**Issue by siddhant1** [prisma/prisma-examples#290]
I think we should add a flexibility to auth by passing a boolean to the utils function and throwing an error if auth is required.

**Comment by nikolasburk** [comment]
Hey @siddhant1, could you be a bit more specific as to **what example(s)** you're referring to and **what your solution would look like**?

**Comment by siddhant1** [comment]
```js
const getUserId = (request, requireAuth = true) => {
  const header = request.request
    ? request.request.headers.authorization
    : request.connection.context.Authorization;
  if (header) {
    const token = header.replace("Bearer ", "");
    const decoded = jwt.verify(token, "thisissupersecrettoo");
    return decoded.userId;
  }
  if (requireAuth) {
    throw new Error("Authentication Required");
  }
  return null;
};

**Comment by siddhant1** [comment]
I would like to pass in a requireAuth boolean to throw error if required.

**Comment by nikolasburk** [comment]
Hey @siddhant1, what's the use case for this? When would you set it to false?

**Comment by siddhant1** [comment]
Sorry for being late.
I had this issue when I was writing a GraphQl API when if a user queries a list of further users it can view his email but not other person's email.
So, in this case, I had to check for the authentication but not throw an error.

**Comment by siddhant1** [comment]
@nikolasburk should I work on it?

**Comment by siddhant1** [comment]
Still waiting for reviews on it

**Comment by 5achinJani** [comment]
@siddhant1 I think in your case having a field level rule auth with [graphql-shield](https://github.com/maticzav/graphql-shield) would work. Let me know if it helps.
[graphql-shield-example](https://github.com/maticzav/graphql-shield/blob/master/examples/advanced/src/permissions/index.ts)
