### ISSUE TITLE
Issue with seed.ts

### ISSUE THREAD

**Issue by ru-van-urk** [prisma/prisma-examples#2902]
Hi all,

I wanted to learn prisma + apollo so I downloaded on of the examples. I downloaded the "GraphQL Server Example (SDL-first)". While testing, the seed data never seemed to work out of the box. 

I found a fix. As stated in (https://www.prisma.io/docs/guides/database/seed-database#compiler-options) I added the compiler options and the seed worked. Maybe this is something missing from the examples? Or am I doing something wrong?

Thanks in advance.

**Comment by ruheni** [comment]
Hey @joxy379 👋🏾

What example did you experience challenges with data seeding? What OS are you running on?

**Comment by ru-van-urk** [comment]
Hi @ruheni 
Its been awhile and now I know how to use seed data correctly. Only with the example it just does not work because it is missing the compiler options as stated in the official docs ( https://www.prisma.io/docs/guides/database/seed-database#compiler-options). The example I used was "graphql-sdl-first" and with Windows as OS.

Thanks for your time!

**Comment by ruheni** [comment]
Minor update: There's an [open issue - #7176](https://github.com/prisma/prisma/issues/7176) - on database seeding specific to Windows and affects all examples. Seeding works fine in other operating systems. 

Thank you for confirming this bug. The engineering team is working on it. 🙂
