### ISSUE TITLE
Is seeding seed.js working from this example?

### ISSUE THREAD

**Issue by BJladika** [prisma/prisma-examples#2923]
I just tried to run from box. Ran all commands and... tried to make a query in playground, but receiving empty array (like there's nothing)
![image](https://user-images.githubusercontent.com/23732658/121019303-420edb80-c7da-11eb-9d73-f2b8b6adf5cb.png)
Maybe seeding must have some additional commands?

**Comment by ruheni** [comment]
Hi @BJladika 👋🏾

What example are you referring to?

**Comment by BJladika** [comment]
Hi @ruheni 
https://github.com/prisma/prisma-examples/tree/latest/javascript/graphql-sdl-first

1) I tried to git clone it (as its written as an alternative), received an error
```
Cloning into 'prisma-examples'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
2) After googling found some solution which downloaded all examples
3) Ran all commands like it was written
```
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20210611141443_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (2.24.1) to .\node_modules\@prisma\client in 335ms
```

and
```
Prisma schema loaded from prisma\schema.prisma
Running seed from "prisma\seed.js" ...

Your database has been seeded.
```
and empty response

**Comment by ruheni** [comment]
You're right! Thank you for catching this. 

Could you provide some additional details, such as the Node.js version and OS you're running on? I want to look into this a little further.

_Seems to work on Linux and not on Windows for some reason._

**Comment by BJladika** [comment]
@ruheni ofc.
Node.js version: 15.8.0
OS Windows 10

**Comment by ruheni** [comment]
This seems to be a bug. I've created an issue in the Prisma repo to track the progress of the bug.

Thank you again!

**Comment by ruheni** [comment]
Seeding was fixed after Prisma 3.x. I'll go ahead and close this issue
