### ISSUE TITLE
AppSync examples

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-examples#293]
We should create some examples on how to use AppSync together with Prisma (probably in Node & TypeScript).

**Comment by DevanB** [comment]
@schickling I'm curious about this. Is this possible? What are the advantages/disadvantages? I might consider implementing this locally for a side project, if it's not too verbose...however, I'm not sure how to even start.

**Comment by nikolasburk** [comment]
I don't think that this is currently possible with Prisma 2 since we don't support AppSync as a data source. Let's keep these examples in mind for when we have an appropriate connector, closing this for now 👍

**Comment by schickling** [comment]
I was rather thinking of an AppSync example that uses Prisma to implement resolver functions.
