### ISSUE TITLE
BEST PRACTICES for paginate using Prisma ORM + Advanced types (include, select...) 

### ISSUE THREAD

**Issue by felinto-dev** [prisma/prisma-examples#2953]
Hello!

I would see examples about how to use Prisma + Pagination.

I already created a topic about it:
https://github.com/prisma/prisma/discussions/7770

I checked the examples from this git repository but I didn't found any code related to pagination I am trying to do it but I am facing some issues with TypeScript Types.

**Comment by ruheni** [comment]
Hi @felinto-dev 👋🏾

We have included pagination with the backend REST and GraphQL examples. For the REST examples, there's a `feed` endpoint that accepts `take` and `skip` query parameters that specify how many objects should be returned and how many of the returned objects in the list should be skipped, respectively. The GraphQL examples have a `feed` query that accepts similar arguments as the REST `feed` endpoint.

In case you run into any issues, don't hesitate to let us know. We would also be happy to get your feedback on how to approach pagination. 🙂

**Comment by ruheni** [comment]
Hey Felinto 👋🏽

I would refer you to our docs on [pagination](https://www.prisma.io/docs/concepts/components/prisma-client/pagination) in the meantime. Feel free to re-open this issue if you have further questions.
