### ISSUE TITLE
Remaining Examples

### ISSUE THREAD

**Issue by abhiaiyer91** [prisma/prisma-examples#3]
- [x] flow-graphql
- [x] flow-script
- [x]  go-graphql
- [ ] go-rest
- [ ] go-raw-db-access [ON HOLD]
- [x] node-cli-app
- [x] node-graphql
- [x] node-graphql-auth
- [x] node-graphql-auth-advanced (should include permissions-with-shield)
- [x] node-graphql-subscriptions 
- [x] node-graphql-schema-delegation
- [x] node-script
- [x] node-rest-express
- [ ] node-raw-db-access [ON HOLD]
- [x]  typescript-cli-app
- [x]  typescript-graphql
- [x]  typescript-graphql-auth
- [ ]  typescript-graphql-auth-advanced (should include permissions-with-shield)
- [x]  typescript-graphql-subscriptions
- [x]  typescript-graphql-schema-delegation
- [x]  typescript-script
- [ ] typescript-raw-db-access [ ON HOLD]

**Comment by herkulano** [comment]
It would be nice to have a `many-to-many` example.

Something simple like unread posts of a user. This would be enough to understand the datamodel, the api schema and the resolvers needed.

`datamodel.prisma`:
```graphql
type User {
  id: ID! @unique

  email: String @unique
  name: String!

  posts: [Post!]!
  unreads: [Unread!]! @relation(name: "UserUnreads")
}

type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!

  title: String!
  isPublished: Boolean! @default(value: "false")
  body: String
  author: User

  unreads: [Unread!]! @relation(name: "PostUnreads")
}

type Unread {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!

  user: User! @relation(name: "UserUnreads")
  post: Post! @relation(name: "PostUnreads")
}
```

**Comment by Sach97** [comment]
+1 to @herkulano proposition that way we can see things like nested object writes in action (I'm struggling with createMany in golang-client as it is not yet documented)

**Comment by amesas** [comment]
There was an example of S3 Integration.
I think it's a good idea to keep it.
