### ISSUE TITLE
End-to-End tests for fullstack examples

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma-examples#3059]
Add end-to-end tests using Playwright, preferably for fullstack examples.

This would boost our confidence in the applications.

- Let's save the test inside https://github.com/prisma/prisma-examples/tree/latest/.github/tests. You can create a new folder called e2e and call the file `test.spec.ts` (just a suggestion)
- Once the test is ready, update the relevant bash scripts in https://github.com/prisma/prisma-examples/tree/latest/.github/tests/javascript and https://github.com/prisma/prisma-examples/tree/latest/.github/tests/typescript by adding the command to run the script `npx playwright test __PATH_TO_TEST_/test.spec.ts `

**Comment by pshaddel** [comment]
Hi @ruheni 
I would like to help solve this issue for some of the examples. What is your opinion about using Cypress?

**Comment by ruheni** [comment]
Hey @pshaddel,

That's awesome! I would prefer Playwright because it doesn't require any configuration to run

**Comment by pshaddel** [comment]
OK,
I will start working on [first full stack example](https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes). Wish me luck with my first contribution in Prisma world :)

**Comment by ruheni** [comment]
A few pointers that may help,

- Let's save the test inside https://github.com/prisma/prisma-examples/tree/latest/.github/tests. You can create a new folder called e2e and call the file `test.spec.ts` (just a suggestion)
- Once the test is ready, update the relevant bash scripts in https://github.com/prisma/prisma-examples/tree/latest/.github/tests/javascript and https://github.com/prisma/prisma-examples/tree/latest/.github/tests/typescript by adding the command to run the script `npx playwright test __PATH_TO_TEST_/test.spec.ts `


In case you need any help, let me know.

**Comment by pshaddel** [comment]
Thanks for the heads up. I took a look at the documentation of playwright. I think we are going to use [@playwright/test](https://playwright.dev/docs/test-annotations#group-tests) and we are not going to use third parties like `jest` or `jasmine`.

**Comment by ruheni** [comment]
That's correct. It'll be just a single file with groups of tests 🙂
