### ISSUE TITLE
Does it support the Apollo Server 3?

### ISSUE THREAD

**Issue by tedwong** [prisma/prisma-examples#3090]
As title.

**Comment by janpio** [comment]
There currently is no example project using Apollo Server 3.x. 
Replacing the 2.x with 3.x obviously also does not work out of the box: https://github.com/prisma/prisma-examples/pull/3016
But there is no reason why upgrading the project to 3.x properly should not work.

**Comment by m-abdelwahab** [comment]
I just updated the examples to use Apollo Server 3

- https://github.com/prisma/prisma-examples/tree/latest/javascript

**Comment by m-abdelwahab** [comment]
@tedwong I just updated the examples to use Apollo Server 3 

# JavaScript:
- [GraphQL with Nexus](https://github.com/prisma/prisma-examples/tree/latest/javascript/graphql)
- [GraphQL Auth](https://github.com/prisma/prisma-examples/tree/latest/javascript/graphql-auth)
- [GraphQL SDL](https://github.com/prisma/prisma-examples/tree/latest/javascript/graphql-sdl-first)

# TypeScript
- [GraphQL Auth](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-auth)
- [GraphQL with Nexus](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql)
- [GraphQL with TypeGraphQL](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-typegraphql)
- [GraphQL with TypeGraphQL CRUD](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-typegraphql-crud)
- [GraphQL SDL](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-sdl-first)
