### ISSUE TITLE
Add missing examples

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#311]
- typescript
  - [x] script
  - [x] graphql
  - [x] graphql-auth
  - [ ] graphql-subscriptions
  - [x] rest
  - [x] cli
- node
  - [x] script
  - [x] graphql
  - [x] graphql-auth
  - [x] graphql-subscriptions
  - [x] rest
  - [x] cli
- golang
  - [x] script
  - [x] graphql
  - [ ] graphql-auth
  - [ ] graphql-subscriptions
  - [x] rest
  - [x] cli
- flow
  - [x] script
  - [x] graphql
  - [ ] graphql-auth
  - [ ] graphql-subscriptions
  - [ ] rest
  - [ ] cli

**Comment by phoenicxai** [comment]
ExpertAI-AgentAutomatedPrismaAgent
