### ISSUE TITLE
Apollo-server V3 -->> prisma-examples/typescript/graphql-subscriptions,???

### ISSUE THREAD

**Issue by jcherrabi** [prisma/prisma-examples#3138]
Hello there,
can someone please share an typescript example for the graphql-subscription using Apollo0Server V3 as the e example below is build for v2.x since PubSub was removed in V3 according to the docs.

prisma-examples/typescript/graphql-subscriptions/

Thank you,

**Comment by ruheni** [comment]
closed in #3439
