### ISSUE TITLE
typescript/rest-nextjs-express unusable

### ISSUE THREAD

**Issue by hefekranz** [prisma/prisma-examples#3142]
Hey there, sadly this example is pretty broken (maybe just for me?)

There is no initial data nor an applied schema, so the backend crashes when fetching posts. I fixed this by creating and applying a migration.

Also, fetch will fail without cors enabled in express, I fixed by installing the cors plugin.

Pretty new to prisma, but at the very least the README needs to be updated. 
Cheers

**Comment by ruheni** [comment]
Hey @hefekranz 👋🏾 

Thanks for taking note of this. I just tried it out, and it's missing a step and a `seed.ts` beside the error you encountered. I'll create a task list to update the example.

- [x] Add `seed.ts` file
- [x] Add `migrate dev` and and `db seed` steps in the README
- [x] Fix CORS issue
