### ISSUE TITLE
Feature: Use NPX Over Global Deps

### ISSUE THREAD

**Issue by iamclaytonray** [prisma/prisma-examples#315]
Instead of having users install prisma globally, can we consider using NPX instead? It's easier to manage versions and does not clutter up the global disk. (It also slightly lowers the barrier-to-entry. Not much but every little bit counts)

If you give this the go-ahead, I'll refactor the READMEs & package.json's to reflect the changes. IE:

```json
"scripts": {
    "start": "npx ts-node src/index.ts",
    "prisma": "npx prisma",
    "generate": "npx graphqlgen"
  },
```

And users would simply type `yarn prisma [command]`

**Comment by nikolasburk** [comment]
Hey @iamclaytonray, thanks so much for sharing your thoughts. We have actually thought _a lot_ about this internally and with the latest examples overhaul we've decided to:

- Consistently require users to install the Prisma CLI globally
- Include all other dependencies (e.g. graphqlgen) as dev dependencies and invoke them via a script defined in package.json

The reasoning for the global installation of the Prisma CLI is that we don't want to have any abstraction between the user and the Prisma CLI, they should use it _directly_. Before reworking the examples, we included Prisma as a dev dependency and have received the feedback that it was confusing (especially for beginners) to use `yarn prisma [command]` instead or just `prisma [command]` which is seen in the docs. Another important point here is that we want all examples to be _consistent_ and _idiomatic_ to their respective language. While it's _possible_ to use `npx` for the Go-examples, it's not definitely not _idiomatic_. Go examples instruct the users to install the Prisma CLI via Homebrew and there's no way to include it as a dev dependency. 

Please let me know if you have any further questions!
