### ISSUE TITLE
Add example for GraphQL-based microservices

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma-examples#322]
I would love to see an example implementing GraphQL-based microservices with different databases and of course using an API gateway as the main entry point for client apps.

I suggest to add it into the official documentation or host it on "examples" folder in this repository.

**Comment by otrebu** [comment]
@schickling @marktani anyone working on completing this example?

**Comment by dohaicuong** [comment]
Apparently, Apollo release their new tools to build API gateway and microservices.
I create a repository putting Apollo Federation and Prisma together.
https://github.com/dohaicuong/prisma-microservices

**Comment by jferrettiboke** [comment]
@dohaicuong Thanks for sharing this.

One thing concerned me, though. How can Prisma ensure distributed transactions when using microservices? We should have events or something to communicate with other services.

**Comment by jferrettiboke** [comment]
@dohaicuong Thanks for sharing this.

One thing concerns me, though. How can Prisma ensure distributed transactions when using microservices? We should have events or something to communicate with other services.

**Comment by dohaicuong** [comment]
Sorry for the late reply.

That's what I've been looking at.
So I could say event driven is a good approach in this case, or something like Saga to ensure the distributed transactions would make sense. However, I think there is no silver bullet for distributed system like this.

Or we can see if there any supports from prisma team about the good approach for this maybe :))

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
