### ISSUE TITLE
Consider using `next-graphql` if it's useful in Next.js + GraphQL examples

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#3286]
https://github.com/ian/next-graphql

![image](https://user-images.githubusercontent.com/4058327/138885460-d03ef575-1d7d-4528-a4a7-49193dd99ef8.png)

**Comment by ruheni** [comment]
Current set up uses GraphQL Yoga which is relatively _future proof_. I'll go ahead and close the issue
