### ISSUE TITLE
No authorization in rest-nextjs-api-routes-auth example?

### ISSUE THREAD

**Issue by HermanNygaard** [prisma/prisma-examples#3297]
```ts
// DELETE /api/post/:id
export default async function handle(req: NextApiRequest, res: NextApiResponse) {
  const postId = req.query.id;
  if (req.method === "DELETE") {
    const post = await prisma.post.delete({
      where: { id: Number(postId) },
    });
    res.json(post);
  } else {
    throw new Error(
      `The HTTP ${req.method} method is not supported at this route.`
    );
  }
}
```
In the frontend you check ` const postBelongsToUser = session?.user?.email === props.author?.email;` in order for an user to send the delete request, but if you do it with Postman anyone can delete any post unless I'm missing something?

**Comment by ruheni** [comment]
Hi @HermanNygaard 👋🏽

Thank you for raising this issue in the PR. 

I've made some changes to the example in the linked PR to protect POST `/post` PUT `/publish/:id`, and DELETE `/post/:id`. Let me know if you have any further suggestions for the example. 🙂
