### ISSUE TITLE
example aws-lambda no longer working

### ISSUE THREAD

**Issue by tobkle** [prisma/prisma-examples#3308]
Local Environment:
```zsh
OSX: Monterey 12.0.1 (M1)
Node: v15.5.0
Framework Core: 2.65.0
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.17.2
```
Tried to get this [approach from prisma docu](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda) working. But it looks like the original aws-lambda example is deprecated:

1. There is no query-engine-*
```zsh
package:
  patterns:
    - '!node_modules/.prisma/client/query-engine-*'
    - 'node_modules/.prisma/client/query-engine-rhel-*'
```
... but a libquery-engine-*. So I assume serverless.yml should contain the following instead:
```zsh
package:
    patterns:
        - "!node_modules/.prisma/client/libquery-engine-*"
        - "node_modules/.prisma/client/libquery-engine-rhel-*"
```

2. That file libquery_engine-rhel-openssl-1.0.x.so.node has a size of 44 MB. This in turn  lead to the following error during ```sls deploy```:
```zsh
Serverless Error ----------------------------------------
 
  An error occurred: GetUsersLambdaFunction - Resource handler returned message: 
"Unzipped size must be smaller than 262144000 bytes" 
(Service: Lambda, Status Code: 400, HandlerErrorCode: InvalidRequest).
```

Has anyone a working aws-lambda prisma example setup, which is working?

Tried that [article](https://itnext.io/lets-take-prisma-2-for-a-test-drive-on-aws-lambda-with-graphql-%EF%B8%8F-f4be711e93cc), but it isn't working any more. It is refering this 2 year old [example](https://github.com/dested/OrbitalGa.me/tree/master/server), which sounds promising, but so far I couldn't get it deployed.

**Comment by janpio** [comment]
Have a look at this currently open PR that updates the pattern: https://github.com/prisma/docs/pull/2477
Can you confirm it works with this one?

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale. 

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
