### ISSUE TITLE
typescript/graphql-typegraphql-crud no longer works

### ISSUE THREAD

**Issue by dsmurl** [prisma/prisma-examples#3356]
I'm getting a problem with the typegraphql example here:

https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-typegraphql-crud

error when migrating where no @generated stuff is created -> 
    Error: Generator at typegraphql-prisma could not start:

Maybe it has something to do with the typegraphql additions in their 0.18.  I can't tell.

**Comment by ruheni** [comment]
Hey @dsmurl 👋🏽

I can't seem to replicate this on my end. Can you try updating to the latest versions of Prisma and typegraphql-prisma` (0.18.1)? Let me know if you are still running into the same issue 🙂

**Comment by dsmurl** [comment]
Sure

**Comment by dsmurl** [comment]
Ok so out of the box with the following repro I get ->

Repro:

 - git clone git@github.com:prisma/prisma-examples.git
 - cd prisma-examples/typescript/graphql-typegraphql-crud
 - yarn
 - yarn prisma migrate dev --name init
    - results in output containing: Error: Looks like an incorrect version "3.5.0" of the Prisma packages has been installed

Possible fix which seems to work:

 package.json update of prisma and the client like this:

```
{

  "name": "graphql-typegraphql-crud",
  "version": "1.0.0",
  "scripts": {
    "dev": "ts-node-dev --no-notify --respawn --transpile-only src/index.ts"
  },
  "dependencies": {
    "@prisma/client": "3.6.0",
    "@types/graphql-fields": "1.3.4",
    "apollo-server": "3.5.0",
    "class-validator": "0.13.2",
    "graphql": "15.7.2",
    "graphql-fields": "2.0.3",
    "graphql-type-json": "0.3.2",
    "reflect-metadata": "0.1.13",
    "type-graphql": "1.1.1"
  },
  "devDependencies": {
    "@types/graphql": "14.5.0",
    "@types/node": "16.11.11",
    "@types/ws": "8.2.1",
    "prisma": "3.6.0",
    "ts-node": "10.4.0",
    "ts-node-dev": "1.1.8",
    "typegraphql-prisma": "0.18.1",
    "typescript": "4.5.2"
  },
  "prisma": {
    "seed": "ts-node prisma/seed.ts"
  }
}
```

I was seeing other stuff the other day but it seems closer and easily fixed now.

**Comment by dsmurl** [comment]
Looks like prisma and client change from 3.5 to 3.6 works well.
