### ISSUE TITLE
Unable to compile TypeScript when adding the t.field('profile' portion to the User object type function

### ISSUE THREAD

**Issue by epratt-yb** [prisma/prisma-examples#3385]
I am trying to get the graphQL server example working, but when I add the following from section 2.1:

```
t.field('profile', {
     type: 'Profile',
     resolve: (parent, _, context) => {
       return context.prisma.user.findUnique({
         where: { id: parent.id }
        }).profile()
      }
    })
```

I get the following error:

```
[ERROR] 19:50:48 ⨯ Unable to compile TypeScript:
src/schema.ts:238:5 - error TS1005: ',' expected.

238    t.field('profile', {
        ~
```

Not sure how to get around this.

**Comment by ruheni** [comment]
Hey 👋🏽

Based on the error, a `,` is missing right before the `t.field('profile', ...`. We've also updated the `graphql` example to use Pothos instead of Nexus. I'll go ahead and close the issue in the meantime.
