### ISSUE TITLE
Add more docker examples

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-examples#345]
The following docker examples are missing:

- [ ] `docker-mysql-new`
- [ ] `docker-mysql-existing`
- [ ] `docker-postgres-new`
- [ ] `docker-postgres-existing`

**Comment by nikolasburk** [comment]
@schickling can you clarify what the `X-existing` examples should look like? Should the only difference be that they have set the `migrations` property to `false` in their Docker Compose file? Also note that this only works for the `postgres` connector but doesn't yet work with `mysql`.

**Comment by schickling** [comment]
As just discussed offline, it makes sense to just keep the `X-new` examples and link to the respecting getting started docs for existing databases.

**Comment by nikolasburk** [comment]
Added 6 more examples:

 - Node
  - `docker-mysql`
  - `docker-postgres`
 - TypeScript
  - `docker-mysql`
  - `docker-postgres`
 - Go
  - `docker-mysql`
  - `docker-postgres`
