### ISSUE TITLE
Incorrect TypeGraphQL (code-first) example in UserResolver

### ISSUE THREAD

**Issue by samrumi** [prisma/prisma-examples#3518]
**Example Issue**

findMany() function will return an array of User i.e `[User]`. But in the example allUsers() query returns a User.

<img width="543" alt="Screen Shot 2022-02-06 at 10 05 15 AM" src="https://user-images.githubusercontent.com/87925236/152687243-2eeb221d-eb34-42ca-8e1a-c44652d6b297.png">

**Correction**

```ts
@Resolver(User)
export class UserResolver {
  @Query((returns) => [User], { nullable: true })
  async allUsers() {
    return prisma.user.findMany()
  }
} 
```

**Where?**

https://www.prisma.io/graphql 
TypeGraphQL (code-first) section

**Comment by ruheni** [comment]
Thanks, @sarumi for catching this. We'll fix this :)
