### ISSUE TITLE
Problem with launching the example TS graphql-next : cannot find mondule node_modules/next/dist/shared/lib/constants.js

### ISSUE THREAD

**Issue by getzelus** [prisma/prisma-examples#3546]

**Comment by getzelus** [comment]
Hello, I followed the read me doc. 
I downloaded the package and inside,
npm install
npx prisma migrate dev --name init
npm run dev

But after it doesnt launch and I have this bug : 

Server Error
Error: Cannot find module '../../../../graphql-nextjs/node_modules/next/dist/shared/lib/constants.js'
Require stack:
- D:\react\proj\graphql-nextjs\.next\server\pages\_document.js
- D:\react\proj\graphql-nextjs\node_modules\next\dist\server\require.js
- D:\react\proj\graphql-nextjs\node_modules\next\dist\server\load-components.js
- D:\react\proj\graphql-nextjs\node_modules\next\dist\build\utils.js
- D:\react\proj\graphql-nextjs\node_modules\next\dist\build\output\store.js
- D:\react\proj\graphql-nextjs\node_modules\next\dist\build\output\index.js
- D:\react\proj\graphql-nextjs\node_modules\next\dist\cli\next-dev.js
- D:\react\proj\graphql-nextjs\node_modules\next\dist\bin\next

**Comment by ruheni** [comment]
Hi, @getzelus 👋🏾 

I can't seem to reproduce the error you're experiencing. Could you provide further details on your setup such as the OS you're on, the Node.js and npm version you're running on as well

Could you retry and let me know if you're still experiencing the issue?
