### ISSUE TITLE
Problem sign in with "rest-nextjs-api-routes-auth" example

### ISSUE THREAD

**Issue by vipinlahoti** [prisma/prisma-examples#3559]
<img width="455" alt="Screenshot 2022-02-25 at 12 21 05" src="https://user-images.githubusercontent.com/2918394/155668470-4fe53e69-5c66-4490-bc64-9f0ef141e9f8.png">

<img width="442" alt="Screenshot 2022-02-25 at 12 24 34" src="https://user-images.githubusercontent.com/2918394/155668920-6de411d2-a02e-4670-abc7-cd2f3bbf7643.png">

just creates a user, no error/warning is observed on console.
Any help would be appreciated.

**Comment by ruheni** [comment]
Hi, @vipinlahoti 👋🏾 

I'll look into this and update the example –  you can re-open the issue if you're still experiencing the error 🙂
