### ISSUE TITLE
Next.js seeding still fails at unique emails

### ISSUE THREAD

**Issue by cyrusae** [prisma/prisma-examples#3666]
I seem to be having a similar error to [this one](https://github.com/prisma/prisma-examples/issues/3250) and [this one](https://github.com/prisma/prisma-examples/issues/3450), with a copy of the Next.js/Prisma/Express example downloaded today.

Terminal output (on Mac OSX 11.6) is:
```
Running seed command `ts-node prisma/seed.ts` ...
Start seeding ...
PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
/Users/[FOLDERS REDACTED]/backend/prisma/seed.ts:54:36

   51 async function main() {
   52   console.log(`Start seeding ...`)
   53   for (const u of userData) {
→  54     const user = await prisma.user.create(
  Unique constraint failed on the fields: (`email`)
    at Object.request (/Users/watcher/[FOLDERS REDACTED]/backend/node_modules/@prisma/client/runtime/index.js:45578:15)
    at async PrismaClient._request (/Users/[FOLDERS REDACTED]/backend/node_modules/@prisma/client/runtime/index.js:46405:18) {
  code: 'P2002',
  clientVersion: '3.12.0',
  meta: { target: [ 'email' ] }
}

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts
```
(obviously with the full file path instead of `[FOLDERS REDACTED]` in the original terminal)

Everything before that worked fine; I'm not familiar enough with Prisma et al. yet to know if I can go ahead with just what was generated by the first `seed` command (my target database is completely different, if that helps, but I decided to start with the example and overwrite with different dummy data as I go), or really to know anything else about how to proceed from here. Thanks in advance for any help and apologies if there's other applicable duplicates I failed to find.

**Comment by ruheni** [comment]
Hi @cyrusae 👋🏽

Could you outline the commands you ran before you ran into the error?

When you run `npx prisma migrate dev` the first time, it creates the database and then seeds the database if a seed script is present. If you run `npx prisma db seed` after `migrate dev`, the seed would fail because the email field is unique.

If you have any further questions, let me 🙂

**Comment by cyrusae** [comment]
Hi @ruheni, I was following the instructions from Prisma in order, so while I don't have that terminal window any more that may imply there is a repeat?

**Comment by ruheni** [comment]
Hey, cyrusae 👋🏽

I've updated the README for the `rest-nextjs-express` example. Let me know if you run into any further issues.
