### ISSUE TITLE
Missing `dev.db` files in all examples

### ISSUE THREAD

**Issue by denik1981** [prisma/prisma-examples#3689]
Can someone please restore the `dev.db` files that were deleted in #2624?
What was the purpose of deleting them?

**EDIT:** I think I understand what's the purpose but it's not quite intuitive to someone working with the examples.
It will be nice to have a post-installation step (`package.json`) that executes `prisma generate && prisma db push` to leave you with a clean installation to start the server.

**Comment by ruheni** [comment]
Hi 👋🏽,

Thanks for the feedback! The post-installation step is running `npx prisma migrate dev --name init` – which also sets up the database. We expect the learner/ developer to run the command independently to understand the moving pieces. The READMEs for the examples serve as a tutorial with sequential steps the learner would follow.

But I think it would be worth improving the wording we use in our examples to explain when the database is set up – happy to hear your suggestions.
