### ISSUE TITLE
CockroachDB example doesn't use migrate

### ISSUE THREAD

**Issue by haaarshsingh** [prisma/prisma-examples#3690]
https://github.com/prisma/prisma/issues/4702
https://github.com/prisma/prisma/releases/tag/3.11.0

As of Prisma release 3.11.0, running `prisma migrate` is now supported with CockroachDB, although the example provided in this repository is still using two schema files and a `dbinit.sql` file with `prisma db pull` to generate the schema as opposed to simply running migrate.

# Suggested Fix

As CockroachDB and SQL server are both relational databases, it'd be a good idea for the CockroachDB example to mirror it as the SQL server example has both relations and some level of complexity.

**Comment by haaarshsingh** [comment]
Closed due to #3691 :tada:

**Comment by janpio** [comment]
Thanks for the help @harshhhdev!
