### ISSUE TITLE
Error deploying to Aws-lambda. ReferenceError: WeakRef is not defined

### ISSUE THREAD

**Issue by Alpa84** [prisma/prisma-examples#3963]
Following the [Deploying to AWS Lambda](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda) guide results in the following error when executing the function:

> ReferenceError: WeakRef is not defined
    at LibraryEngine.loadEngine (/var/task/node_modules/@prisma/client/runtime/index.js:25224:26)
    at async LibraryEngine.instantiateLibrary (/var/task/node_modules/@prisma/client/runtime/index.js:25185:5) {
  clientVersion: '4.1.0'
}

Steps to reproduce: 

- Follow the  [Deploying to AWS Lambda](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda) guide
- Execute `getUsers` function
- Check the function logs `serverless logs -f getUsers`
- Result:
  > ReferenceError: WeakRef is not defined
    at LibraryEngine.loadEngine (/var/task/node_modules/@prisma/client/runtime/index.js:25224:26)
    at async LibraryEngine.instantiateLibrary (/var/task/node_modules/@prisma/client/runtime/index.js:25185:5) {
  clientVersion: '4.1.0'
}

**Comment by Alpa84** [comment]
Updating the Node runtime to use `nodejs16.x` in [line 8 of the serverless.yml file](https://github.com/prisma/prisma-examples/blob/latest/deployment-platforms/aws-lambda/serverless.yml#L8) solves the issue

**Comment by janpio** [comment]
Node 14.x should be enough, we dropped support for Node 12 in Prisma v4: https://github.com/prisma/prisma/releases/tag/4.0.0

@ruheni Are we lacking tests for `deployment-platforms/aws-lambda`?

**Comment by ruheni** [comment]
We currently don't test any of the `deployment-platform` examples. I'll look into this.
