### ISSUE TITLE
NestJS example

### ISSUE THREAD

**Issue by pschaub** [prisma/prisma-examples#4000]
The example in the official NestJS documentation is different from the example on the prisma website.

## Current NestJS documentation
See https://docs.nestjs.com/recipes/prisma#use-prisma-client-in-your-nestjs-services
```ts
import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
```
There is an additional note on the NestJS documentation:
> NOTE
The onModuleInit is optional — if you leave it out, Prisma will connect lazily on its first call to the database. We don't bother with onModuleDestroy, since Prisma has its own shutdown hooks where it will destroy the connection. For more info on enableShutdownHooks, please see [Issues with enableShutdownHooks](https://docs.nestjs.com/recipes/prisma#issues-with-enableshutdownhooks)

## Current Prisma example
See https://www.prisma.io/nestjs

```ts
import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {
  async onModuleInit() {
    await this.$connect();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }
}
```

**Comment by ruheni** [comment]
Hey @pschaub 👋🏽

Thanks for reporting this! We've updated the code snippet on the page. :)
