### ISSUE TITLE
npx generate fails

### ISSUE THREAD

**Issue by lterfloth** [prisma/prisma-examples#402]
I updated all my dependencies and copied the typescript-auth starter while using a local docker container as the prisma endpoint. 

Using "prisma deploy" runs "prisma generate" sucessfully but "npx nexus-prisma-generate" fails and logs the error "No valid 'prisma-client-dir' was found". 

I went through all the recent changes and can't find a solution to my problem. I assume there's something wrong with the example.

**Comment by Weakky** [comment]
Hey, apologize for the inconvenience.

`nexus-prisma-generate` was indeed updated, and as we're using it via `npx` we forgot to update the examples here. This is soon gonna be fixed.

As @funthomas suggested, this is indeed the right fix.

`nexus-prisma-generate` now takes two arguments:

- `prisma-client-dir` which is the directory where your prisma client is located
- `output-dir` which is where you want the types to be saved

**Comment by lterfloth** [comment]
@funthomas @Weakky thank your for your suggestions. The fix works like a charm, cheers!

**Comment by Weakky** [comment]
FYI, `nexus-prisma-generate` now takes named argument such as:

`npx nexus-prisma-generate --client ./src/generated/prisma-client --output ./src/generated`

Also, `--output` now expects a directory and not a file.

Closing this 🙌
