### ISSUE TITLE
Add example to mock Database for Expressjs API test

### ISSUE THREAD

**Issue by Sirjoseph94** [prisma/prisma-examples#4089]
Hi,

I have been trying to figure out how to mock a database and use it to test my API built with Expressjs. I am running the test with Jest and Supertest.

It will be nice to have an example to guide me.

**Comment by ruheni** [comment]
Hi 👋🏽

My colleague worked on an [guide to mocking with Prisma](https://www.prisma.io/blog/testing-series-1-8eRB5p0Y8o) I would recommend you to look at. Here's the [example repo](https://github.com/sabinadams/express_sample_app) used in the guide.

I'll create a GitHub issue listing all the examples we could add to this repository.I'll the meantime, I'll go ahead and close the issue.
