### ISSUE TITLE
Go-graphql example docker-compose file & Scaffolding

### ISSUE THREAD

**Issue by Sach97** [prisma/prisma-examples#41]
Hi prisma team, is it possible to put the docker-compose file in the go-graphql example instead of the one with prisma deployed endpoint ? Plus I have a lot of errors with the generated code when switching to my own prisma server with the way you scaffolded it as it is not scaffoled like this with gqlgen init.

**Comment by Sach97** [comment]
Thank's a lot I appreciate it

**Comment by abhiaiyer91** [comment]
https://github.com/prisma/prisma-examples/pull/42 @Sach97

**Comment by Sach97** [comment]
Thank's @abhiaiyer91 it worked like a charm. I made my own example on [this repo](https://github.com/Sach97/prisma-go-todo) with a readme explaining the dev workflow with go-client. And developer experience with Prisma is great btw, thank's to the team for the great work !
