### ISSUE TITLE
typegraphql-prisma-crud has an error

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#4193]
😡😡😡

```
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: graphql-typegraphql-crud@1.0.0
npm ERR! Found: @prisma/client@4.0.0
npm ERR! node_modules/@prisma/client
npm ERR!   @prisma/client@"4.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @prisma/client@"~4.4.0" from typegraphql-prisma@0.22.0
npm ERR! node_modules/typegraphql-prisma
npm ERR!   dev typegraphql-prisma@"0.22.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/nikolasburk/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nikolasburk/.npm/_logs/2022-10-25T10_19_06_026Z-debug.log
```

**Comment by janpio** [comment]
Interesting that this works on CI: 
https://github.com/prisma/prisma-examples/actions/runs/3370295687/jobs/5591031146
https://github.com/prisma/prisma-examples/actions/runs/3367053607/jobs/5584182546

**Comment by ruheni** [comment]
I looked into this and I discovered that CI uses yarn to install dependencies and generate Prisma Client

Yarn seems to resolve the peer dependency issue automatically but npm doesn't. I've already started working on this and I've made some improvements to the tests here: https://github.com/prisma/prisma-examples/pull/4194 🤔

**Comment by ruheni** [comment]
After a little digging, it seems we're intentionally skipping the Prisma version check in CI for the typegraphql-prisma generator — [docs](https://github.com/MichalLytek/typegraphql-prisma/blob/fc7cfa756a60dd6671a902c38f00ee74698a681a/Readme.md#lifting-prisma-version-restriction)

GitHub action: 
```
# .github/workflows/test.yaml
env:
	# other env vars
  SKIP_PRISMA_VERSION_CHECK: true # Skip Prisma version check in typegraphl-prisma (https://github.com/MichalLytek/typegraphql-prisma/blob/fc7cfa756a60dd6671a902c38f00ee74698a681a/Readme.md#lifting-prisma-version-restriction)
```

`typegraphql-prisma` docs:
![image](https://user-images.githubusercontent.com/33921841/200329054-10b1dcb5-d486-462a-a55b-820950759953.png)

**Comment by ruheni** [comment]
Suggested workaround: Not ideal but, I'm going to add the `--legacy-peer-deps` flag  npm install step to ensure it works for all users and perhaps a note explaining the current behaviour in the example README file
