### ISSUE TITLE
I have a problem with prisma

### ISSUE THREAD

**Issue by cabiamdos** [prisma/prisma-examples#4278]
I was following a tutorial with graphql when prisma was at version1 and it was so easy, no prisma migrate or anything, it was just `prisma deploy` and that it was.

And when you where defining schema in "datamodel.graphql" (using postgres as the db) the queries (post, postsConnections) and mutation (createPost,updatePost,deletePost,upsertPost,updateManyPosts)
just by adding this lines
```
type Post {
  id: ID! @unique
  title: String!
  body: String!
  published: Boolean!
  author: User!
}
```
And now I was following the documentation [https://github.com/prisma/prisma-examples/tree/latest/javascript/graphql#using-the-graphql-api](url) and you have to do a bunch of things.

You need to implement the schema.prisma (the model), then run a migration, then update all the queries and mutations by using a framework called nexus, and then exporting all the added stuff.  Then I see your youtube video on what is prisma (prisma.io) and it is like in version 1

Literally before in version 1 it was easy, how can I access the features of version 1 in version 4 of prisma?

Now when following prisma in version 4, and so many frameworks and things you need to track on its more difficult than in version 1....

**Comment by nikolasburk** [comment]
Hey there, thanks for your feedback @cabiamdos!

> Now when following prisma in version 4, and so many frameworks and things you need to track on its more difficult than in version 1....

This observation is correct, the differences between Prisma 1 and Prisma 2 are explained [here](https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/how-to-upgrade#main-differences-between-prisma-1-and-prisma-version-2x-and-later). The TLDR is that Prisma 2+ is an ORM whereas Prisma 1 was a "GraphQL generator".

If your goal is to stand up a GraphQL API for a database without writing any code on the backend, Prisma might not be the right tool for you (even though this can still be done using tools like the [TypeGraphQL CRUD generator](https://dev.to/prisma/prototyping-a-crud-api-with-typegraphql-and-prisma-for-your-database-424c)) and [you might be better off with Postgraphile or Hasura](https://www.prisma.io/docs/concepts/overview/should-you-use-prisma#-you-want-a-crud-graphql-api-without-writing-any-code).

Hope this helps!

**Comment by cabiamdos** [comment]
Thanks for the answer. I will keep studying prisma v1 and prisma v2 and try to find which is better for me.
