### ISSUE TITLE
Improve Next.js examples

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#4312]
- [ ] Add "Deploy with Vercel" button
- [ ] issue: README talking about an API route that doesn’t exist (`/api/feed`)

**Comment by ruheni** [comment]
Idea: Link to the [fullstack-prisma-nextjs-blog template](https://github.com/prisma/fullstack-prisma-nextjs-blog) from the example README.

We'll have to switch the database provider if we want to add a deploy button. SQLite doesn't work too well on Vercel with Prisma. The last time I tried it, I ran into some errors — the SQLite file could not be found.

I would like to understand the purpose and intention we have with the Next.js examples to help decide if we should(n't) add the deploy button.

Here are some of the options I think we have:
Option 1: Add a deploy button, and update the database provider to make the deployment process smoother.

Option 2: No deployment button but link to [fullstack-prisma-nextjs-blog template](https://github.com/prisma/fullstack-prisma-nextjs-blog) from the README.

**Comment by ruheni** [comment]
Another suggestion:
- [x] Improve data serialization with `superjson` and `next-superjson`. We currently use a [utility function](https://github.com/prisma/prisma-examples/blob/latest/typescript/rest-nextjs-api-routes/lib/util.ts) to serialize `DateTime` values. Guide: https://flaviocopes.com/nextjs-serialize-date-json/

**Comment by mayank1513** [comment]
Also needs refactor
