### ISSUE TITLE
Suggestion: `testing-express` with multiple database sources

### ISSUE THREAD

**Issue by brunolnetto** [prisma/prisma-examples#4326]
Hello, Prisma!

There is a non-zero chance of this issue being rejected by the human-brain-bot. 

First of all, I thank Prisma for the multiple use cases on their plural combinations. In particular,  I like this [use case](https://github.com/prisma/prisma-examples/tree/latest/typescript/testing-express) with a web package (e.g. express, but could be `fastify` or `koa` as well) because it is very insightful on this [_open source_ boilerplate](https://github.com/trouchet/sappio) I learn-develop.

My request regards the provision of clarification and, if possible, feature request on: 

- database initialization steps according to the operating system and database sources (current: [`postgresql`, `mysql`, `sqlite`, `sqlserver`, `mongodb`, `cockroachdb`]): on the abovementioned example, there is a binary-file `prisma/dev.db`, which assumes a Linux user (a hopeful assumption ;-) ). It is a great development practice, but obscure this step I mention;
- examples with other database sources and suggestive database tools.

**Comment by janpio** [comment]
The binary is just a SQLite database - that should work on all platforms.

**Comment by brunolnetto** [comment]
I see, my bad. :-S

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
