### ISSUE TITLE
graphql-apollo-server directs us to the graphql example, which doesn't use apollo

### ISSUE THREAD

**Issue by katyho** [prisma/prisma-examples#4334]
https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-apollo-server directs to the graphql example https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql

However, this example uses GraphQL Yoga instead of Apollo Server. Looking through the commit history of this example, the last commit to use Apollo was 10 days ago here: https://github.com/prisma/prisma-examples/tree/7aa021616a5e7c305b1d7e28b7b9f8b34f82f744/typescript/graphql

**Comment by ruheni** [comment]
Hey @katyho 👋🏽

Thanks for the reminder. The `typescript/graphql` example should link to https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nexus instead. I'll make the update. 🙂
