### ISSUE TITLE
Infer and explicitly declare types for client extensions

### ISSUE THREAD

**Issue by halbano** [prisma/prisma-examples#4344]
When declaring Prisma client extensions, the types are not inferred properly. 

The extensions, when being called, are showing typescript errors related with the no detection of the declared extensions: 

<img width="1673" alt="Screen Shot 2022-12-22 at 22 50 39" src="https://user-images.githubusercontent.com/5341623/209254933-7bdecef4-f570-4951-b536-8180401162dc.png">

Did folks work on anything similar and were able to type all this correctly? Is there any example of how this should work?

**Comment by ruheni** [comment]
Hi @halbano,

Thanks for reporting the issue. I recommend you post/ transfer your issue to the https://github.com/prisma/prisma repo with a snippet of your extension and the type error you're running into. 🙂
