### ISSUE TITLE
Prisma Example of how to create a reusable NPM package

### ISSUE THREAD

**Issue by bojank** [prisma/prisma-examples#4370]
It would be awesome to have one data project that i can reuse in all my services and actual app. I think this would be probably the most common use case for a lot of more complex setups but there is not much guides on how to achieve something like this.

I found this but its very outdated.
https://isidoro-ferreiro.medium.com/share-your-prisma-client-across-projects-44d1c7aca6fd

I also found this but am running into an issue where i cant install the package because its trying to bundleDep the node_modules/.prisma folder and thats not a valid name for NPM as in the one issue that exists on that repo.
https://github.com/MarcMogdanz/typed-prisma-package

its trying to make a prisma package that has a bundleDependencies which its trying to add a folder .prisma
"bundledDependencies": [
    "@prisma/client",
    ".prisma"
  ]

keep getting this error
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".prisma" of package ".prisma@*": name cannot start with a period.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏

**Comment by husayt** [comment]
this is still the major issue with apps deployed to cloud. Once app is built before deploying  prisma generates .prisma in node_modules and places it inside package.json. When that  project is deployed and cloud run `npm i` it throws above error.
