### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by astha-nimblechapps** [prisma/prisma-examples#462]
Hello,

I need to improve the performance of query and mutation as fast as we can, is there any way to do so?. Please help me out I am stuck. 

Thanks

**Comment by nikolasburk** [comment]
Hey @astha-nimblechapps, thanks a lot for opening this issue. Would you mind sharing what example you're referring to? In case you're seeking general help with Prisma, please ask your question in the [Prisma forum](https://www.prisma.io/forum/) or open an issue in the main [Prisma repo](https://github.com/prisma/prisma).

**Comment by astha-nimblechapps** [comment]
> Hey @astha-nimblechapps, thanks a lot for opening this issue. Would you mind sharing what example you're referring to? In case you're seeking general help with Prisma, please ask your question in the [Prisma forum](https://www.prisma.io/forum/) or open an issue in the main [Prisma repo](https://github.com/prisma/prisma).

yes sure I got the solution 

Thanks
