### ISSUE TITLE
rest-nextjs-api-routes-auth CLIENT_FETCH_ERROR

### ISSUE THREAD

**Issue by qunders** [prisma/prisma-examples#4733]
Hi there.

I'm following the documentation to test out the `rest-nextjs-api-routes-auth` example.
Logging in through Github seems to work fine, however when I write a new draft and post it, it redirects to the drafts page, but no new entry has been made. In the dev console I see the following error

```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error undefined {
  error: {},
  url: 'http://localhost:3000/api/auth/session',
  message: undefined
}
```

The NextAuth docs explain the error as follows

> If you see CLIENT_FETCH_ERROR make sure you have configured the NEXTAUTH_URL environment variable.

In my .env file, NEXTAUTH_URL is defined as follows

`NEXTAUTH_URL='http://localhost:3000'`

Any help is greatly appreciated

**Comment by karimovrenat** [comment]
HI.  I had the same problem.  Do you resolve it?

**Comment by wdsAnders** [comment]
I honestly don't remember. I think i just ditched it, and went for a different approach - sorry i can't help

**Comment by karimovrenat** [comment]
thank you for an answer

вт, 20 июн. 2023 г. в 10:53, Anders ***@***.***>:

**Comment by bullcherry** [comment]
You can solve this problem to use getServerSession instead of getSession on 'api/post/index.ts'.
[https://next-auth.js.org/getting-started/example#backend---api-route](https://next-auth.js.org/getting-started/example#backend---api-route)
