### ISSUE TITLE
Error in examples "Build an App"

### ISSUE THREAD

**Issue by vadymkukhtinOD** [prisma/prisma-examples#483]
While going through the example see one bug in examples:

[URL](https://www.prisma.io/docs/1.26/get-started/03-build-graphql-servers-with-prisma-TYPESCRIPT-t201/#explore-the-graphql-api-in-a-playground)

On third Example "Publish a Post" - there is a bug.
It should be referring to "id" but not "postId" to work properly

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @vadymkukhtinOD, I just the fixed the sample mutation in the docs 🙌
