### ISSUE TITLE
graphql.NewOrderedMap is undefined

### ISSUE THREAD

**Issue by maiguangyang** [prisma/prisma-examples#493]
prisma-examples/go/graphql/server/generated.go

./generated.go:495:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:657:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:886:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:1145:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:1320:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:1493:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:1618:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:1840:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:1977:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap
./generated.go:2214:9: undefined: "github.com/99designs/gqlgen/graphql".NewOrderedMap

**Comment by tkallioras** [comment]
I have the same issue as well. Has anybody found a solution?

**Comment by clarkbrent** [comment]
The example you're referring to in particular seems to require the use of the [dep management tool](https://github.com/golang/dep). Doing a simple `go get` doesn't seem to work like in a few of the other examples I messed around with.

It's worth mentioning though that managing dependencies through modules seems to be the way the golang project is going to handle dependencies [starting in 1.13 (~August 2019)](https://blog.golang.org/modules2019).
