### ISSUE TITLE
Update NestJS examples to no longer use beforeExit hook

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma-examples#4931]
This hook was removed in Prisma 5 and unfortunately is in basically all Nest/Prisma documentation.

**Comment by okonon** [comment]
@jharrell quick question if i have this in my application what are the implications of just removing this?
```
 async enableShutdownHooks(app: INestApplication): Promise<void> {
    await this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}
```

**Comment by jharrell** [comment]
@okonon thanks for the question! AFAIK you can remove that block without any implications. `app.enableShutdownHooks()` should be sufficient.
