### ISSUE TITLE
Node GraphQL Example, mutation cannot be executed

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-examples#50]
For the `node-graphql` example, the `createDraft` mutation cannot be executed. For example, try to run this mutation:

```graphql
mutation b {
  createDraft(title: "Title" content: "Content" authorEmail: "nilan@nilan.nilan") {
    id
  }
}
```

you will get the error message:

```json
{
  "data": null,
  "errors": [
    {
      "message": "No Node for the model User with value 'nilan@nilan.nilan' for email found.",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "createDraft"
      ],
      "code": 3039,
      "requestId": "local:api:cjmal9soq000i0b83z8ckqei0"
    }
  ]
}
```

The reason is that no author exists yet. However, there is no mutation to create a new author either.
This should be cleaned up.

Current workaround: directly connect to the Prisma endpoint and create a new user:

```
mutation a {
  createUser(data: {
    name: "Nilan"
    email: "nilan@nilan.nilan"
  }) {
    email
  }
}
```

Then the first mutation works.

**Comment by abhiaiyer91** [comment]
All examples are seeded with a user alice@prisma.io. We can change the docs to make that clear
