### ISSUE TITLE
nuxtjs3 - db.ts example code does not match the referenced documentation page

### ISSUE THREAD

**Issue by schalkneethling** [prisma/prisma-examples#5106]
In the `db.ts` file here https://github.com/prisma/prisma-examples/blob/latest/typescript/rest-nuxtjs/prisma/db.ts the code links to the following document:

https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices

However, the code in `db.ts` does not match the code on the page above.

1. Are the differences intentional and specific to Nuxtjs?
2. If so, we might want to create a separate page on the docs site that is Nuxt-specific.
3. If not, which of the two examples should be considered correct and best practice?

I am happy to help with updating the docs, but I would first need to understand the lay of the land, so to speak. 😃

**Comment by ruheni** [comment]
👋

Thanks for raising this. We recently updated the docs but haven't updated the examples yet. We'd welcome a PR to update the Prisma Examples. 🙂
