### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by OmkarMS** [prisma/prisma-examples#535]
I tried to query in graphql playground and I get error on terminal----
Server is running on http://localhost:4000
TypeError: Only absolute URLs are supported

and in playground, when I try to fire----

```graphql
mutation CreatePrismaLink {
  post(
    description: "Prisma turns your database into a GraphQL API 😎",
    url: "https://www.google.com"
  ) {
    id
  }
}
```

```graphql
mutation CreateApolloLink {
  post(
    description: "The best GraphQL client for React",
    url: "https://www.google.com"
  ) {
    id
  }
}
```

I get the result as ---

```json
{
  "data": null,
  "errors": [
    {
      "message": "Only absolute URLs are supported",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "post"
      ]
    }
  ],
  "extensions": {}
}
```

**Comment by vistriter** [comment]
@OmkarMS If you set up prisma endpoint by env you must install dotenv and set config. :rocket:

<img width="680" alt="Screen Shot 2562-03-28 at 23 41 56" src="https://user-images.githubusercontent.com/24702575/55176164-33b4e600-51b3-11e9-8f76-29796f056ac7.png">

**Comment by gabrielruss** [comment]
I would just like to add to this just in case someone else comes along with my same problem. I had `require('dotenv').config()` in my file along with `const { prisma } = require('./generated/prisma')` but I had them in the wrong order. You have to put the dotenv config BEFORE the prisma declaration.
