### ISSUE TITLE
Resolver not implemented

### ISSUE THREAD

**Issue by MANJUSAK** [prisma/prisma-examples#562]
start:
`query accessMenu($where: AccessMenuWhereUniqueInput!) {
  accessMenu(where: $where) {
    id
  }
}
{
  "where": {
    "id": "123"
  }
}`
result:
`{
  "errors": [
    {
      "message": "Resolver not implemented",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "accessMenu"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Resolver not implemented",
            "    at accessMenu (D:\\workspace\\renhe\\venom\\venom-runtime\\src\\generated\\placeholder\\resolvers\\Query.ts:9:11)",
            "    at field.resolve (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql-extensions\\src\\index.ts:267:18)",
            "    at resolveFieldValueOrError (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:480:18)",
            "    at resolveField (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:447:16)",
            "    at executeFields (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:294:18)",
            "    at executeOperation (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:238:122)",
            "    at executeImpl (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:85:14)",
            "    at Object.execute (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:62:35)",
            "    at D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\apollo-server-core\\src\\requestPipeline.ts:367:28",
            "    at Generator.next (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "accessMenu": null
  }
}`

**Comment by nikolasburk** [comment]
Hey @MANJUSAK, thanks a lot for opening this issue 🙂 could you please provide a bit more information about your problem:

- Which example are you referring to?
- At which step in the README of the example does the error occur?

**Comment by MANJUSAK** [comment]
@nikolasburk 

Thank you very much for your answer. The problem has been found and has been resolved.

The parser needs to be its own implementation method
E.g
` categories: (parent, args, ctx) => {
    console.log('args--------->', args)
    return ctx.prisma.categories(args)
  },
  categoriesConnection: (parent, args, ctx) => {
    throw new Error('Resolver not implemented')
  }`
