### ISSUE TITLE
Namespacing/nesting queries and mutations in schema with Nexus and Shield

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma-examples#567]
Hey!

Thanks for the examples, they are super helpful 👏 

I'm evaluating Nexus and Shield, and have taken the `graphql-auth` project as a starter example. I've got the project up and running, and was trying to figure out how namespacing the schema would work - for example, nest all `User` related queries and mutations under a `User` namespace, so instead of 

```
mutation {
  login...
}
```

one would do

```
mutation {
  user {
    login...
  }
}
```

Same goes for queries, where one would, for example, put the `feed`, `post` and `filterPosts` queries under a `post` namespace, i.e.

```
{
  post {
    feed...
    filterPosts...
  }
}
```

However, I can't figure out how to 
1. Do that in Nexus - what would the return type of the new 'root' type (i.e. the `post` namespace for queries) be?
2. Is that even possible with Shield? It throws errors at me as soon as I try to make a deeper level of keys in the permissions, i.e. go from

```
export const permissions = shield({
  Query: {
    me: rules.isAuthenticatedUser,
    filterPosts: rules.isAuthenticatedUser,
    post: rules.isAuthenticatedUser,
  },
  Mutation: {...},
});
```

to

```
export const permissions = shield({
  Query: {
    me: rules.isAuthenticatedUser,
    posts: {
      filterPosts: rules.isAuthenticatedUser,
      post: rules.isAuthenticatedUser,
    }
  },
  Mutation: {...},
});
```

Not sure if this is the right place to post it @maticzav @schickling  ?

**Comment by jhalborg** [comment]
Not stale, just low prio I think :D

**Comment by maticzav** [comment]
Not stale

**Comment by jhalborg** [comment]
Still not stale, go away stale bot! 😄

**Comment by nikolasburk** [comment]
Hey @jhalborg, apologies for the huge delay on this 🙏  this actually seems like a question about Neuxs and Shield rather than an issue with the specific example (at least that's my interpretation 😅). Do you mind reposting your question in the `nexus` and `graphql-shield` repos since that should probably be answered by the repo owners?

**Comment by jhalborg** [comment]
Hey @nikolasburk - Sorry, I totally forgot about this. After some more research, I found [this discussion](https://github.com/graphql/graphql-spec/issues/163) in the `graphql-spec` repo. It seems this is not a viable path for now, so I'll close this issue

**Comment by nikolasburk** [comment]
Great, thanks a lot! 🙏
