### ISSUE TITLE
PULSE_API_KEY="__YOUR_PULSE_API_KEY__"

### ISSUE THREAD

**Issue by putty-kang** [prisma/prisma-examples#6124]
PULSE_API_KEY="__YOUR_PULSE_API_KEY__",   What is this, can we not do this?

**Comment by jharrell** [comment]
Hi there! 

Are you referring to the pulse starter example? If so, you can find that key in the [Prisma Console](https://console.prisma.io)

https://github.com/prisma/prisma-examples/blob/fefa99d62ea2aa39359905421ee05ac7dc802e3c/pulse/starter/README.md?plain=1#L5-L10
