### ISSUE TITLE
zeit now example with zero config

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-examples#742]
Make the Prisma 2 + zeit's now example zero config: https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/zeit-now

**Comment by divyenduz** [comment]
Works via https://github.com/prisma/prisma-examples/pull/745

**Comment by martonlanga** [comment]
Hey @divyenduz, would it be possible to deploy the `graphql-auth` example with `photon.js` to the zeit platform?

**Comment by janpio** [comment]
Best open an issue over at https://github.com/prisma/prisma2 @martonlanga Thanks.
