### ISSUE TITLE
Typescript sample - prismaObjectType is not a function

### ISSUE THREAD

**Issue by Jermorin** [prisma/prisma-examples#825]
Hi guys !

I've an issue with Typescript sample (graphql-auth) when I launch the service seems that the lib was updated but not the usage in the code

```
npm start

> graphql-auth@ start /Users/jermorin/Workspace/prisma-examples/typescript/graphql-auth
> ts-node-dev --no-notify --respawn --transpileOnly ./src

Using ts-node version 8.4.1, typescript version 3.6.3
TypeError: nexus_prisma_1.prismaObjectType is not a function
```

Do I forget something ?

Thanks in advance

**Comment by tombarton** [comment]
@Jermorin the `nexus-prisma` package has been updated in the last couple of days. As part of this update, they have dropped support for Prisma 1.0 ([see here](https://github.com/prisma-labs/nexus-prisma/releases/tag/v0.4.1)). To get things working again with the existing documentation, downgrade your version of `nexus-prisma` to `0.3.8`.

**Comment by jeremy-kreditech** [comment]
Hi ! Its exactly that I did after looking git logs, and obviously work better. Should be a good idea to downgrade it in the package.json to assure that when you git clone you don't have to downgrade manually as I did ?

Thanks for your response

**Comment by Jermorin** [comment]
Hi ! Its exactly that I did after looking git logs, and obviously works better. Could be a good idea to downgrade it in the package.json to assure that when you git clone you don't have to downgrade manually as I did ?

Thanks for your response
