### ISSUE TITLE
npm run signupUser failed

### ISSUE THREAD

**Issue by imVinayPandya** [prisma/prisma-examples#826]
I have created new project using javascript + gRPC. I ran npm start and npm run singupUser

i was giving me the something like "Instead of where, you should add data object". I have made this change on localhost and it worked.

Here is the code ref: https://github.com/prisma/prisma-examples/blob/1d4e05b1c769c741e12e02e72441e19c8f5d6ef7/javascript/grpc/server/server.js#L60

I am happy to submit the PR for this.

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @imVinayPandya 🙌 this should now be fixed, feel free to reopen the issue if it still doesn't work for you.
