### ISSUE TITLE
docker example does not work for Darwin (OSX) users

### ISSUE THREAD

**Issue by haysclark** [prisma/prisma-examples#844]
The `docker` example does not work for Darwin (OSX) users due to the fact that there is no pre-compiled version of bcrypt@3.0.6 for Node 12.4.0 currently.

https://github.com/prisma/prisma-examples/blame/prisma2/deployment-platforms/docker/Dockerfile#L1

A workaround is to roll back to Node v10.16.3:

```
FROM node:10.16.3
...
```

**Comment by pantharshit00** [comment]
Can you please raise a PR changing `bcrypt` to `bcryptjs`? That would be helpful for us.

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @haysclark 🙏 

We'll be fixing the Docker example soon, I created another issue to track this here: https://github.com/prisma/prisma-examples/issues/1437
