### ISSUE TITLE
Generated typeDefs misses the /* GraphQL */ comment

### ISSUE THREAD

**Issue by brikou** [prisma/prisma-examples#9]
Adding `/* GraphQL */` comment allows syntax highlighting:

**Before**

![image](https://user-images.githubusercontent.com/383212/45374310-fa8b9e80-b5f1-11e8-9e3b-61599d245432.png)

**After**

![image](https://user-images.githubusercontent.com/383212/45374314-feb7bc00-b5f1-11e8-8758-328d92752b78.png)

WDYT?

**Comment by brikou** [comment]
BTW this file exports typeDefs, do why not call it typeDefs.ts instead of graphql.ts? It would make it more predictable IMHO.

**Comment by timsuchanek** [comment]
@brikou thanks for that point! We're thinking about renaming it to `schema.ts` - what do you think about that?

**Comment by brikou** [comment]
@timsuchanek for me schema and typeDefs is not the same, a schema should be a GraphQLSchema instance and this is not, it will be after makeSchemaExecutable (if I remember well), I think typeDefs.ts is still relevant IMO.

**Comment by abhiaiyer91** [comment]
We have updated the name of the generated file:`prisma-schema` and includes the GraphQL comment for typeDefs.
