### ISSUE TITLE
Sapper / Polka example

### ISSUE THREAD

**Issue by soullivaneuh** [prisma/prisma-examples#905]
Is it possible to have a Sapper / Polka setup Prisma2 example?

See: https://sapper.svelte.dev/

**Comment by ruheni** [comment]
Hey 👋🏽

We've created a couple examples using Sveltekit that might interest you.
- `javascript/rest-sveltekit`: https://github.com/prisma/prisma-examples/tree/latest/javascript/rest-sveltekit
- `typescript/rest-sveltekit`: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-sveltekit
- `typescript/sveltekit`: https://github.com/prisma/prisma-examples/tree/latest/typescript/sveltekit

I'll go ahead and close the issue in the meantime.
