### ISSUE TITLE
Docker example build fail due to POSTGRESQL_URL environment variable

### ISSUE THREAD

**Issue by lvauvillier** [prisma/prisma-examples#916]
in docker example, `Step 9/13 : RUN prisma2 generate` fails.

I have the following error:

```
Error: Schema parsing error: Environment variable not found: POSTGRESQL_URL.
  -->  /opt/app/prisma/schema.prisma:4
   | 
 3 |   // Like, postgresql://user:password@localhost:5432/database/schema
 4 |   url      = env("POSTGRESQL_URL")
 5 | }
   | 
```

why url is needed at build time?

**Comment by nikolasburk** [comment]
Hey @lvauvillier 👋 thanks a lot for opening this issue and apologies for the delay. The error seems to suggest that the `POSTGRESQL_URL` environment variables hasn't been set. Can you confirm that the error still persists even if the environment variable is set? You can try this:

```
export POSTGRESQL_URL=postgresql://USER:PASSWORD@HOST:5432/DATABASE
```

You'll need to replace the placeholders that are spelled in uppercase letters with your own DB connection details. Please feel free to reopen the issue if you're still seeing the error after setting the environment variable.

**Comment by nikolasburk** [comment]
Actually I just tried this myself and even when the env var is set it indeed didn't get picked up by Docker... I also tried adjusting the `run` command in the `Makefile` to add the env var there manually using:

```make
run:
  docker run -it -p 8080:8080 -e POSTGRESQL_URL=postgresql://USER:PASSWORD@HOST:5432/DATABASE  ${DOCKER_IMAGE}
```

We'll look into this soon!

**Comment by lvauvillier** [comment]
Hi @nikolasburk, the -e option is used to set environment variables only when running the container.
The error raises when I try to build the container. A workaround is to add `ENV POSTGRESQL_URL ""` in the dockerfile.

I don't understand why prisma needs this env var to generate the client in the postinstall script...

**Comment by nikolasburk** [comment]
> the -e option is used to set environment variables only when running the container.
The error raises when I try to build the image. A workaround is to add ENV POSTGRESQL_URL "" in the dockerfile.

Ha, thanks for the clarification! 🙏 

> I don't understand why prisma needs this env var to generate the client in the postinstall script...

It's needed because the DB connection string must be included in the generated Photon.js code, so it needs to be there at generation time. Does that make sense?

**Comment by lvauvillier** [comment]
Yes, of course, it makes sense. But at this point, (build time) there is no need to evaluate the variable, no ?

The workaround works with an empty string. I think prisma doesn't need to know the value of the environment var to generate the client. It just needs to know that the final value will be provided thought this variable.

**Comment by tvvignesh** [comment]
Hi. Faced the same issue even on my end today. Was trying to get Photon running on Docker. It makes sense to include the url if the db is being introspected to generate code, but my guess is that, its not (that's something lift does as I understand).

So, it can just be replaced in the generated code without evaluating the value thus not needing the value of db connection at build time. Hope it makes sense.

**Comment by tvvignesh** [comment]
My current workaround was not to run `prisma2 generate` in the Dockerfile but do it in the machine then checkin to source control along with it, so that the `prisma2 generate` command is never run on the server thus not requiring the env. After the container starts, photon will use the env I passed at run time.

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @lvauvillier  🙏 

We'll be fixing the Docker example soon, we created another issue to track this here: https://github.com/prisma/prisma-examples/issues/1437
