### ISSUE TITLE
Replace `seed.graphql` files with seed scripts (e.g. `node seed.js`)

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-examples#94]
We should replace the `seed.graphql` files with more language-idiomatic seed scripts using the generated Prisma client.

**Comment by schickling** [comment]
This currently blocked by this issue: https://github.com/prisma/prisma/issues/3226

**Comment by schickling** [comment]
As prisma/prisma#3596 is fixed and released, this issue should not be unblocked @nikolasburk  🚀

**Comment by schickling** [comment]
@nikolasburk is this indeed done?

**Comment by nikolasburk** [comment]
It's done for all examples except the Go Docker examples, let's leave it open until that's they're also done 👍
