### ISSUE TITLE
Example - using Prisma Client's $subscribe 

### ISSUE THREAD

**Issue by valentinbe** [prisma/prisma-examples#96]
Hi, 
Could you please provide an example on generating REST api client side subscription using  Prisma Client's $subscribe? 

I cant figure out a way to properly listen to CRUD events using $subscribe.
```ts
const el = await prisma.$subscribe.message().node();
el.next().then(e => console.log(e)); // <-- This only works for the next event, how can i listen to all future events instead?
```

**Comment by nikolasburk** [comment]
Hey @valentinbe, could you be a bit more specific on what exactly? `el` is an `AsyncIterator`, so `next()` is the natural way to interact with it.
