### ISSUE TITLE
Photon Typescript not working properly

### ISSUE THREAD

**Issue by AlexandruSerban142** [prisma/prisma-examples#971]
In the examples, if you use in a resolver ctx.photon. you don't get autosuggesions about the models you have available in schema.prisma. I suppose the problem is comming from the typegenAutoConfig in makeSchema, but I don't know how to solve it. A solution would be greatly appreciated.

**Comment by nikolasburk** [comment]
Hey @AlexandruSerban142, thanks a lot for opening this issue. The problem should be fixed now, feel free to reopen the issues if you still don't see the autocompletion 🙂
