### ISSUE TITLE
Typescript demo - Build not working

### ISSUE THREAD

**Issue by dizzyn** [prisma/prisma-examples#974]
In the examples the demo "graphql-apollo-server" can not be builded.

- pull the demo
- `npm install`
- `npx prisma2 dev`
- `npm rund build` <== return errors:

````
You should specify a configuration value for outputs in Nexus' makeSchema. Provide one to remove this warning.
src/schema.ts:7:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

7     t.model.id()
        ~~~~~

src/schema.ts:8:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

8     t.model.name()
        ~~~~~

src/schema.ts:9:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

9     t.model.email()
        ~~~~~

src/schema.ts:10:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

10     t.model.posts({
         ~~~~~

````

(`npm run dev` works fine)

Thank You

**Comment by YouWillBe** [comment]
![image](https://user-images.githubusercontent.com/16474244/69255501-e4646f80-0bf2-11ea-8bb0-c1a921638689.png)
It seems to be the same problem

**Comment by martonlanga** [comment]
Installing this version of nexus somehow works for me:
"nexus": "0.12.0-beta.14"

**Comment by martonlanga** [comment]
Newest version that's working for me is: `0.12.0-rc.3`, but now I get a TS error saying that the plugin is incompatible in `makeSchema`:
```
// The expected type comes from property 'plugins' which is declared here on type 'SchemaConfig'
plugins: [nexusPrismaPlugin()],
```

**Comment by nikolasburk** [comment]
Hey @dizzyn and @martonlanga, this should be fixed now! Please try again if this was fixed with the latest changes for you as well and feel free to reopen the issue if the errors are still there 🙂 🙏

**Comment by martonlanga** [comment]
Thanks @nikolasburk, it works now! Specifying `outputs` in `makeSchema` & generating did it 🙃
